export function useAppRuntimeCoreArgs({ state, setters, ui, runtime, refs, helpers }) {
  return {
    state: {
      ...state,
      tab: ui.tab,
    },
    setters: {
      setReady: setters.setReady,
      setCloudSync: setters.setCloudSync,
      setHoldings: setters.setHoldings,
      setTradeLog: setters.setTradeLog,
      setTargets: setters.setTargets,
      setFundamentals: setters.setFundamentals,
      setWatchlist: setters.setWatchlist,
      setAnalystReports: setters.setAnalystReports,
      setReportRefreshMeta: setters.setReportRefreshMeta,
      setHoldingDossiers: setters.setHoldingDossiers,
      setNewsEvents: setters.setNewsEvents,
      setAnalysisHistory: setters.setAnalysisHistory,
      setReversalConditions: setters.setReversalConditions,
      setStrategyBrain: setters.setStrategyBrain,
      setBrainValidation: setters.setBrainValidation,
      setResearchHistory: setters.setResearchHistory,
      setPortfolioNotes: setters.setPortfolioNotes,
      setDailyReport: setters.setDailyReport,
    },
    ui: {
      resetTransientUiState: ui.resetTransientUiState,
      setReviewingEvent: ui.setReviewingEvent,
      setReviewForm: ui.setReviewForm,
    },
    runtime: {
      flashSaved: runtime.flashSaved,
      requestAppConfirmation: runtime.requestAppConfirmation,
    },
    refs: {
      activePortfolioIdRef: refs.activePortfolioIdRef,
      viewModeRef: refs.viewModeRef,
      portfoliosRef: refs.portfoliosRef,
      portfolioSetterRef: refs.portfolioSetterRef,
      bootRuntimeRef: refs.bootRuntimeRef,
      cloudSyncStateRef: refs.cloudSyncStateRef,
      cloudSaveTimersRef: refs.cloudSaveTimersRef,
    },
    helpers,
  }
}

export function useAppRuntimeWorkflowArgs({
  state,
  derived,
  ui,
  asyncState,
  actions,
  setters,
  resources,
  runtime,
  refs,
  helpers,
}) {
  return {
    state: {
      ready: state.ready,
      viewMode: state.viewMode,
      portfolioViewMode: state.portfolioViewMode,
      activePortfolioId: state.activePortfolioId,
      canUseCloud: state.canUseCloud,
      holdings: state.holdings,
      tradeLog: state.tradeLog,
      marketPriceCache: state.marketPriceCache,
      newsEvents: state.newsEvents,
      analysisHistory: state.analysisHistory,
      strategyBrain: state.strategyBrain,
      portfolioNotes: state.portfolioNotes,
      reversalConditions: state.reversalConditions,
      reportRefreshMeta: state.reportRefreshMeta,
      researchHistory: state.researchHistory,
      analystReports: state.analystReports,
      portfolios: state.portfolios,
      morningNote: state.morningNote,
      dailyReport: state.dailyReport,
    },
    derived: {
      todayMarketClock: derived.todayMarketClock,
      shouldTriggerPostCloseSelfHeal: derived.shouldTriggerPostCloseSelfHeal,
      todayRefreshKey: derived.todayRefreshKey,
      dossierByCode: derived.dossierByCode,
      H: derived.H,
      W: derived.W,
      totalCost: derived.totalCost,
      totalVal: derived.totalVal,
      totalPnl: derived.totalPnl,
      retPct: derived.retPct,
      overviewPortfolios: derived.overviewPortfolios,
      overviewTotalValue: derived.overviewTotalValue,
      overviewTotalPnl: derived.overviewTotalPnl,
      overviewDuplicateHoldings: derived.overviewDuplicateHoldings,
      overviewPendingItems: derived.overviewPendingItems,
      winners: derived.winners,
      losers: derived.losers,
      top5: derived.top5,
      holdingsIntegrityIssues: derived.holdingsIntegrityIssues,
      attentionCount: derived.attentionCount,
      pendingCount: derived.pendingCount,
      targetUpdateCount: derived.targetUpdateCount,
      dataRefreshRows: derived.dataRefreshRows,
      reportRefreshCandidates: derived.reportRefreshCandidates,
      watchlistFocus: derived.watchlistFocus,
      watchlistRows: derived.watchlistRows,
      showRelayPlan: derived.showRelayPlan,
    },
    ui: {
      tab: ui.tab,
      filterType: ui.filterType,
      catalystFilter: ui.catalystFilter,
      scanQuery: ui.scanQuery,
      scanFilter: ui.scanFilter,
      sortBy: ui.sortBy,
      showReversal: ui.showReversal,
      expandedStock: ui.expandedStock,
      relayPlanExpanded: ui.relayPlanExpanded,
      dailyExpanded: ui.dailyExpanded,
      researchTarget: ui.researchTarget,
      reviewForm: ui.reviewForm,
      reviewingEvent: ui.reviewingEvent,
      expandedNews: ui.expandedNews,
    },
    asyncState: {
      analyzing: asyncState.analyzing,
      setAnalyzing: asyncState.setAnalyzing,
      analyzeStep: asyncState.analyzeStep,
      setAnalyzeStep: asyncState.setAnalyzeStep,
      researching: asyncState.researching,
      setResearching: asyncState.setResearching,
    },
    actions: {
      upsertTargetReport: actions.upsertTargetReport,
      upsertFundamentalsEntry: actions.upsertFundamentalsEntry,
      updateReversal: actions.updateReversal,
      updateTargetPrice: actions.updateTargetPrice,
      updateAlert: actions.updateAlert,
      handleWatchlistUpsert: actions.handleWatchlistUpsert,
      handleWatchlistDelete: actions.handleWatchlistDelete,
      cancelReview: actions.cancelReview,
      switchPortfolio: actions.switchPortfolio,
      exitOverview: actions.exitOverview,
    },
    setters: {
      setResearchTarget: setters.setResearchTarget,
      setResearchResults: setters.setResearchResults,
      setReviewForm: setters.setReviewForm,
      setReviewingEvent: setters.setReviewingEvent,
      setAnalystReports: setters.setAnalystReports,
      setReportRefreshMeta: setters.setReportRefreshMeta,
      setNewsEvents: setters.setNewsEvents,
      setStrategyBrain: setters.setStrategyBrain,
      setBrainValidation: setters.setBrainValidation,
      setDailyReport: setters.setDailyReport,
      setAnalysisHistory: setters.setAnalysisHistory,
      setHoldings: setters.setHoldings,
      setLastUpdate: setters.setLastUpdate,
      setTradeLog: setters.setTradeLog,
      setResearchHistory: setters.setResearchHistory,
      setPortfolios: setters.setPortfolios,
      setActivePortfolioId: setters.setActivePortfolioId,
      setViewMode: setters.setViewMode,
      setCloudSync: setters.setCloudSync,
      setShowReversal: setters.setShowReversal,
      setScanQuery: setters.setScanQuery,
      setScanFilter: setters.setScanFilter,
      setSortBy: setters.setSortBy,
      setExpandedStock: setters.setExpandedStock,
      setRelayPlanExpanded: setters.setRelayPlanExpanded,
      setFilterType: setters.setFilterType,
      setCatalystFilter: setters.setCatalystFilter,
      setDailyExpanded: setters.setDailyExpanded,
      setTab: setters.setTab,
      setExpandedNews: setters.setExpandedNews,
    },
    resources: {
      defaultNewsEvents: resources.defaultNewsEvents,
      researchResults: resources.researchResults,
      stockMeta: resources.stockMeta,
      indColor: resources.indColor,
    },
    runtime: {
      flashSaved: runtime.flashSaved,
      requestAppConfirmation: runtime.requestAppConfirmation,
    },
    refs: {
      priceSelfHealRef: refs.priceSelfHealRef,
      syncPostClosePrices: refs.syncPostClosePrices,
      refreshAnalystReportsRef: refs.refreshAnalystReportsRef,
      resetTradeCaptureRef: refs.resetTradeCaptureRef,
      applyPortfolioSnapshot: refs.applyPortfolioSnapshot,
      portfolioTransitionRef: refs.portfolioTransitionRef,
      cloudSyncStateRef: refs.cloudSyncStateRef,
      livePortfolioSnapshot: refs.livePortfolioSnapshot,
    },
    helpers,
  }
}
