import { PORTFOLIO_VIEW_MODE } from '../constants.js'

export function composeAppRuntimeCoreLifecycleArgs({ data, refs, setters, ui, runtime, helpers }) {
  return {
    ...data,
    ...refs,
    ...setters,
    ...ui,
    ...runtime,
    helpers,
  }
}

export function composeAppRuntimeWorkflowsArgs({
  data,
  ui,
  asyncState,
  actions,
  setters,
  resources,
  refs,
  runtime,
  helpers,
}) {
  return {
    ...data,
    ...ui,
    ...asyncState,
    ...actions,
    ...setters,
    ...resources,
    ...refs,
    ...runtime,
    helpers,
  }
}

export function composeAppRuntimeWorkflowInput({
  runtimeState,
  runtimeSetters,
  coreLifecycle,
  portfolioDerived,
  uiState,
  asyncState,
  runtime,
  helpers,
  resources,
  refs,
  portfolioViewMode = PORTFOLIO_VIEW_MODE,
}) {
  return {
    state: {
      ...runtimeState,
      viewMode: coreLifecycle.viewMode,
      portfolioViewMode,
      activePortfolioId: coreLifecycle.activePortfolioId,
      canUseCloud: coreLifecycle.canUseCloud,
      marketPriceCache: coreLifecycle.marketPriceCache,
      portfolios: coreLifecycle.portfolios,
      morningNote: resources.morningNote,
    },
    derived: portfolioDerived,
    ui: {
      tab: uiState.tab,
      filterType: uiState.filterType,
      catalystFilter: uiState.catalystFilter,
      scanQuery: uiState.scanQuery,
      scanFilter: uiState.scanFilter,
      sortBy: uiState.sortBy,
      showReversal: uiState.showReversal,
      expandedStock: uiState.expandedStock,
      relayPlanExpanded: uiState.relayPlanExpanded,
      dailyExpanded: uiState.dailyExpanded,
      researchTarget: uiState.researchTarget,
      reviewForm: uiState.reviewForm,
      reviewingEvent: uiState.reviewingEvent,
      expandedNews: uiState.expandedNews,
    },
    asyncState,
    actions: {
      upsertTargetReport: coreLifecycle.upsertTargetReport,
      upsertFundamentalsEntry: coreLifecycle.upsertFundamentalsEntry,
      updateReversal: coreLifecycle.updateReversal,
      updateTargetPrice: coreLifecycle.updateTargetPrice,
      updateAlert: coreLifecycle.updateAlert,
      upsertThesis: runtime.upsertThesis,
      handleWatchlistUpsert: coreLifecycle.handleWatchlistUpsert,
      handleWatchlistDelete: coreLifecycle.handleWatchlistDelete,
      cancelReview: coreLifecycle.cancelReview,
      switchPortfolio: coreLifecycle.switchPortfolio,
      exitOverview: coreLifecycle.exitOverview,
    },
    setters: {
      ...runtimeSetters,
      setLastUpdate: coreLifecycle.setLastUpdate,
      setPortfolios: coreLifecycle.setPortfolios,
      setActivePortfolioId: coreLifecycle.setActivePortfolioId,
      setViewMode: coreLifecycle.setViewMode,
      setShowReversal: uiState.setShowReversal,
      setScanQuery: uiState.setScanQuery,
      setScanFilter: uiState.setScanFilter,
      setSortBy: uiState.setSortBy,
      setExpandedStock: uiState.setExpandedStock,
      setRelayPlanExpanded: uiState.setRelayPlanExpanded,
      setFilterType: uiState.setFilterType,
      setCatalystFilter: uiState.setCatalystFilter,
      setDailyExpanded: uiState.setDailyExpanded,
      setTab: uiState.setTab,
      setExpandedNews: uiState.setExpandedNews,
      setResearchTarget: uiState.setResearchTarget,
      setResearchResults: uiState.setResearchResults,
      setReviewForm: uiState.setReviewForm,
      setReviewingEvent: uiState.setReviewingEvent,
    },
    resources: {
      defaultNewsEvents: resources.defaultNewsEvents,
      researchResults: uiState.researchResults,
      stockMeta: resources.stockMeta,
      indColor: resources.indColor,
    },
    runtime,
    refs,
    helpers: {
      ...helpers,
      getMarketQuotesForCodes: coreLifecycle.getMarketQuotesForCodes,
    },
  }
}

export function composeAppRuntimeHeaderInput({
  theme,
  sync,
  coreLifecycle,
  portfolioDerived,
  notes,
  asyncState,
  tabs,
  constants,
  ready,
}) {
  return {
    theme: {
      C: theme.C,
      pc: theme.pc,
    },
    sync: {
      cloudSync: sync.cloudSync,
      saved: sync.saved,
      refreshPrices: coreLifecycle.refreshPrices,
      refreshing: coreLifecycle.refreshing,
      copyWeeklyReport: sync.copyWeeklyReport,
      downloadWeeklyReportMarkdown: sync.downloadWeeklyReportMarkdown,
      downloadWeeklyReportHtml: sync.downloadWeeklyReportHtml,
      exportLocalBackup: sync.exportLocalBackup,
      backupFileInputRef: sync.backupFileInputRef,
      importLocalBackup: sync.importLocalBackup,
      priceSyncStatusTone: coreLifecycle.priceSyncStatusTone,
      priceSyncStatusLabel: coreLifecycle.priceSyncStatusLabel,
      activePriceSyncAt: coreLifecycle.activePriceSyncAt,
      lastUpdate: coreLifecycle.lastUpdate,
    },
    pnl: {
      displayedTotalPnl: portfolioDerived.displayedTotalPnl,
      displayedRetPct: portfolioDerived.displayedRetPct,
    },
    portfolio: {
      activePortfolioId: coreLifecycle.activePortfolioId,
      switchPortfolio: coreLifecycle.switchPortfolio,
      ready,
      portfolioSwitching: coreLifecycle.portfolioSwitching,
      portfolioSummaries: coreLifecycle.portfolioSummaries,
      createPortfolio: coreLifecycle.createPortfolio,
      viewMode: coreLifecycle.viewMode,
      exitOverview: coreLifecycle.exitOverview,
      openOverview: coreLifecycle.openOverview,
      showPortfolioManager: coreLifecycle.showPortfolioManager,
      setShowPortfolioManager: coreLifecycle.setShowPortfolioManager,
      renamePortfolio: coreLifecycle.renamePortfolio,
      deletePortfolio: coreLifecycle.deletePortfolio,
    },
    overview: {
      overviewTotalValue: portfolioDerived.overviewTotalValue,
    },
    notes,
    tabs: {
      urgentCount: portfolioDerived.urgentCount,
      todayAlertSummary: portfolioDerived.todayAlertSummary,
      analyzing: asyncState.analyzing,
      researching: asyncState.researching,
      tab: tabs.tab,
      setTab: tabs.setTab,
      workflowCue: tabs.workflowCue ?? null,
    },
    dialogs: {
      portfolioEditor: coreLifecycle.portfolioEditor,
      portfolioDeleteDialog: coreLifecycle.portfolioDeleteDialog,
    },
    constants,
  }
}
