import { OWNER_PORTFOLIO_ID, PORTFOLIO_VIEW_MODE } from '../constants.js'
import { usePortfolioManagement } from './usePortfolioManagement.js'
import { usePortfolioBootstrap } from './usePortfolioBootstrap.js'
import { usePortfolioPersistence } from './usePortfolioPersistence.js'
import { usePortfolioDossierActions } from './usePortfolioDossierActions.js'
import { useWatchlistActions } from './useWatchlistActions.js'
import { useTransientUiActions } from './useTransientUiActions.js'
import { useAppRuntimeSyncRefs } from './useAppRuntimeSyncRefs.js'
import { useAutoEventCalendar } from './useAutoEventCalendar.js'
import {
  useAppBootRuntimeComposer,
  useAppLifecycleRuntimeComposer,
  usePortfolioManagementComposer,
} from './useAppRuntimeComposer.js'
import { usePortfolioSnapshotRuntime } from './usePortfolioSnapshotRuntime.js'
import { useEventLifecycleSync } from './useEventLifecycleSync.js'
import { useMarketData } from './useMarketData.js'
import { useEffect, useRef } from 'react'

export function useAppRuntimeCoreLifecycle({ state, setters, ui, runtime, refs, helpers }) {
  const {
    ready,
    holdings,
    watchlist,
    newsEvents,
    tradeLog,
    targets,
    fundamentals,
    analystReports,
    reportRefreshMeta,
    holdingDossiers,
    analysisHistory,
    dailyReport,
    reversalConditions,
    strategyBrain,
    brainValidation,
    researchHistory,
    portfolioNotes,
    tab,
  } = state

  const {
    setReady,
    setBootstrapState,
    setCloudSync,
    setHoldings,
    setTradeLog,
    setTargets,
    setFundamentals,
    setWatchlist,
    setAnalystReports,
    setReportRefreshMeta,
    setHoldingDossiers,
    setNewsEvents,
    setAnalysisHistory,
    setReversalConditions,
    setStrategyBrain,
    setBrainValidation,
    setResearchHistory,
    setPortfolioNotes,
    setDailyReport,
  } = setters

  const { restoreTabForPortfolio, resetTransientUiState, setReviewingEvent, setReviewForm } = ui
  const { flashSaved, requestAppConfirmation } = runtime
  const {
    activePortfolioIdRef,
    viewModeRef,
    portfoliosRef,
    portfolioSetterRef,
    bootRuntimeRef,
    cloudSyncStateRef,
    cloudSaveTimersRef,
  } = refs

  const {
    createDefaultReviewForm,
    migrateLegacyPortfolioStorageIfNeeded,
    seedJinlianchengIfNeeded,
    ensurePortfolioRegistry,
    applyTradeBackfillPatchesIfNeeded,
    loadPortfolioSnapshot,
    readSyncAt,
    writeSyncAt,
    shouldAdoptCloudHoldings,
    normalizeHoldings,
    buildHoldingPriceHints,
    getPortfolioFallback,
    savePortfolioData,
    buildHoldingDossiers,
    applyMarketQuotesToHoldings,
    normalizeHoldingDossiers,
    normalizeAnalysisHistoryEntries,
    normalizeStrategyBrain,
    normalizeNewsEvents,
    normalizeDailyReportEntry,
    normalizeBrainValidationStore,
    normalizeFundamentalsStore,
    normalizeWatchlist,
    normalizeAnalystReportsStore,
    normalizeReportRefreshMeta,
    clonePortfolioNotes,
    save,
    toSlashDate,
    getEventStockCodes,
    parseSlashDate,
    appendPriceHistory,
  } = helpers

  const { marketDataArgs, portfolioSnapshotArgs } = useAppBootRuntimeComposer({
    holdings,
    watchlist,
    newsEvents,
    portfoliosRef,
    activePortfolioIdRef,
    viewModeRef,
    setHoldings,
    flashSaved,
    requestAppConfirmation,
    ready,
    marketPriceCache: null,
    cloudSyncStateRef,
    portfolioSetterRef,
    setCloudSync,
    tradeLog,
    targets,
    fundamentals,
    analystReports,
    reportRefreshMeta,
    holdingDossiers,
    analysisHistory,
    dailyReport,
    reversalConditions,
    strategyBrain,
    researchHistory,
    portfolioNotes,
    setTradeLog,
    setTargets,
    setFundamentals,
    setWatchlist,
    setAnalystReports,
    setReportRefreshMeta,
    setHoldingDossiers,
    setNewsEvents,
    setAnalysisHistory,
    setReversalConditions,
    setStrategyBrain,
    setBrainValidation,
    setResearchHistory,
    setPortfolioNotes,
    setDailyReport,
    normalizeAnalysisHistoryEntries,
    applyMarketQuotesToHoldings,
    normalizeFundamentalsStore,
    normalizeWatchlist,
    normalizeAnalystReportsStore,
    normalizeReportRefreshMeta,
    normalizeHoldingDossiers,
    normalizeNewsEvents,
    normalizeStrategyBrain,
    normalizeBrainValidationStore,
    normalizeDailyReportEntry,
    clonePortfolioNotes,
    loadPortfolioSnapshot,
    readSyncAt,
    save,
    savePortfolioData,
  })

  const {
    marketPriceCache,
    marketPriceSync,
    lastUpdate,
    setLastUpdate,
    refreshing,
    priceSyncStatusLabel,
    priceSyncStatusTone,
    activePriceSyncAt,
    refreshPrices,
    syncPostClosePrices,
    getMarketQuotesForCodes,
    priceSelfHealRef,
  } = useMarketData(marketDataArgs)

  const { applyPortfolioSnapshot, flushCurrentPortfolio, livePortfolioSnapshot, loadPortfolio } =
    usePortfolioSnapshotRuntime({
      ...portfolioSnapshotArgs,
      marketPriceCache,
    })

  const portfolioManagementArgs = usePortfolioManagementComposer({
    ready,
    ownerPortfolioId: OWNER_PORTFOLIO_ID,
    portfolioViewMode: PORTFOLIO_VIEW_MODE,
    holdings,
    newsEvents,
    portfolioNotes,
    marketPriceCache,
    flushCurrentPortfolio,
    restoreTabForPortfolio,
    resetTransientUiState,
    loadPortfolio,
    flashSaved,
  })

  const {
    portfolios,
    setPortfolios,
    activePortfolioId,
    setActivePortfolioId,
    viewMode,
    setViewMode,
    portfolioSwitching,
    showPortfolioManager,
    setShowPortfolioManager,
    portfolioTransitionRef,
    portfolioSummaries,
    createPortfolio,
    renamePortfolio,
    deletePortfolio,
    portfolioEditor,
    portfolioDeleteDialog,
    switchPortfolio,
    openOverview,
    exitOverview,
  } = usePortfolioManagement(portfolioManagementArgs)

  const {
    canUseCloud,
    runtimeSyncRefsArgs,
    portfolioBootstrapArgs,
    portfolioPersistenceArgs,
    dossierActionArgs,
    watchlistActionsArgs,
    transientUiArgs,
    eventLifecycleArgs,
  } = useAppLifecycleRuntimeComposer({
    ready,
    ownerPortfolioId: OWNER_PORTFOLIO_ID,
    portfolioViewMode: PORTFOLIO_VIEW_MODE,
    holdings,
    newsEvents,
    portfolioNotes,
    marketPriceCache,
    flashSaved,
    restoreTabForPortfolio,
    activePortfolioId,
    viewMode,
    portfolios,
    setPortfolios,
    setActivePortfolioId,
    setViewMode,
    portfolioSwitching,
    tradeLog,
    targets,
    fundamentals,
    watchlist,
    analystReports,
    reportRefreshMeta,
    holdingDossiers,
    analysisHistory,
    dailyReport,
    reversalConditions,
    strategyBrain,
    brainValidation,
    researchHistory,
    marketPriceSync,
    tab,
    cloudSyncStateRef,
    cloudSaveTimersRef,
    activePortfolioIdRef,
    viewModeRef,
    portfoliosRef,
    portfolioSetterRef,
    bootRuntimeRef,
    applyPortfolioSnapshot,
    portfolioTransitionRef,
    getMarketQuotesForCodes,
    normalizeHoldings,
    savePortfolioData,
    buildHoldingDossiers,
    applyMarketQuotesToHoldings,
    normalizeHoldingDossiers,
    normalizeAnalysisHistoryEntries,
    readSyncAt,
    writeSyncAt,
    setReady,
    setBootstrapState,
    setCloudSync,
    setHoldingDossiers,
    setAnalysisHistory,
    setResearchHistory,
    setTargets,
    setFundamentals,
    setWatchlist,
    setReviewingEvent,
    setReviewForm,
    createDefaultReviewForm,
    migrateLegacyPortfolioStorageIfNeeded,
    seedJinlianchengIfNeeded,
    ensurePortfolioRegistry,
    applyTradeBackfillPatchesIfNeeded,
    loadPortfolioSnapshot,
    shouldAdoptCloudHoldings,
    buildHoldingPriceHints,
    getPortfolioFallback,
    setStrategyBrain,
    setNewsEvents,
    setDailyReport,
    normalizeStrategyBrain,
    normalizeNewsEvents,
    normalizeDailyReportEntry,
    setHoldings,
    toSlashDate,
    getEventStockCodes,
    parseSlashDate,
    appendPriceHistory,
  })

  useAppRuntimeSyncRefs(runtimeSyncRefsArgs)
  usePortfolioBootstrap(portfolioBootstrapArgs)
  usePortfolioPersistence(portfolioPersistenceArgs)

  // 自動事件行事曆：boot 完成後載入公共事件（FOMC、央行、財報季、除權息）
  const { fetchAutoEvents } = useAutoEventCalendar({ setNewsEvents })
  const autoEventsFetchedRef = useRef(false)
  useEffect(() => {
    if (ready && holdings.length > 0 && !autoEventsFetchedRef.current) {
      autoEventsFetchedRef.current = true
      const codes = holdings.map((h) => h.code)
      fetchAutoEvents(codes)
    }
  }, [ready, holdings, fetchAutoEvents])

  const { updateTargetPrice, updateAlert, upsertTargetReport, upsertFundamentalsEntry } =
    usePortfolioDossierActions(dossierActionArgs)
  const { upsertWatchlist: handleWatchlistUpsert, removeWatchlist: handleWatchlistDelete } =
    useWatchlistActions(watchlistActionsArgs)
  const { updateReversal, cancelReview } = useTransientUiActions(transientUiArgs)
  useEventLifecycleSync(eventLifecycleArgs)

  return {
    marketPriceCache,
    marketPriceSync,
    lastUpdate,
    setLastUpdate,
    refreshing,
    priceSyncStatusLabel,
    priceSyncStatusTone,
    activePriceSyncAt,
    refreshPrices,
    syncPostClosePrices,
    getMarketQuotesForCodes,
    priceSelfHealRef,
    applyPortfolioSnapshot,
    livePortfolioSnapshot,
    portfolios,
    setPortfolios,
    activePortfolioId,
    setActivePortfolioId,
    viewMode,
    setViewMode,
    portfolioSwitching,
    showPortfolioManager,
    setShowPortfolioManager,
    portfolioTransitionRef,
    portfolioSummaries,
    createPortfolio,
    renamePortfolio,
    deletePortfolio,
    portfolioEditor,
    portfolioDeleteDialog,
    switchPortfolio,
    openOverview,
    exitOverview,
    canUseCloud,
    updateTargetPrice,
    updateAlert,
    upsertTargetReport,
    upsertFundamentalsEntry,
    handleWatchlistUpsert,
    handleWatchlistDelete,
    updateReversal,
    cancelReview,
  }
}
