import { useMemo } from 'react'
import { APP_LABELS } from '../lib/appMessages.js'
import { filterEventsByType, resolveRuntimeNewsEvents } from '../lib/appShellRuntime.js'
import { useAppDailyAnalysisRuntime } from './useAppDailyAnalysisRuntime.js'
import { useAppReportRuntime } from './useAppReportRuntime.js'
import { useAppStressTestRuntime } from './useAppStressTestRuntime.js'
import { useAppEventReviewRuntime } from './useAppEventReviewRuntime.js'
import { useAppTradeRuntime } from './useAppTradeRuntime.js'
import { useAppResearchRuntime } from './useAppResearchRuntime.js'
import { useAppWeeklyReportRuntime } from './useAppWeeklyReportRuntime.js'
import { useAppLocalBackupRuntime } from './useAppLocalBackupRuntime.js'
import { useAppPanelsRuntime } from './useAppPanelsRuntime.js'
import { brainRuleSummary } from '../lib/brainRuntime.js'

export function useAppRuntimeWorkflows({
  state,
  derived,
  ui,
  asyncState,
  actions,
  setters,
  resources,
  runtime,
  refs,
  helpers,
}) {
  const {
    ready,
    viewMode,
    portfolioViewMode,
    activePortfolioId,
    canUseCloud,
    holdings,
    tradeLog,
    marketPriceCache,
    newsEvents,
    analysisHistory,
    strategyBrain,
    portfolioNotes,
    reversalConditions,
    reportRefreshMeta,
    researchHistory,
    analystReports,
    portfolios,
    morningNote,
    dailySnapshotStatus,
    dailyReport,
  } = state

  const {
    todayMarketClock,
    shouldTriggerPostCloseSelfHeal,
    todayRefreshKey,
    dossierByCode,
    H,
    W,
    totalCost,
    totalVal,
    totalPnl,
    todayTotalPnl,
    retPct,
    overviewPortfolios,
    overviewTotalValue,
    overviewTotalPnl,
    overviewDuplicateHoldings,
    overviewPendingItems,
    urgentCount,
    todayAlertSummary,
    winners,
    losers,
    top5,
    holdingsIntegrityIssues,
    attentionCount,
    pendingCount,
    targetUpdateCount,
    dataRefreshRows,
    reportRefreshCandidates,
    watchlistFocus,
    watchlistRows,
    showRelayPlan,
    renderViewMode,
  } = derived

  const {
    tab,
    filterType,
    catalystFilter,
    scanQuery,
    scanFilter,
    sortBy,
    showReversal,
    expandedStock,
    relayPlanExpanded,
    dailyExpanded,
    researchTarget,
    reviewForm,
    reviewingEvent,
    expandedNews,
  } = ui

  const { analyzing, setAnalyzing, analyzeStep, setAnalyzeStep, researching, setResearching } =
    asyncState

  const {
    upsertTargetReport,
    upsertFundamentalsEntry,
    updateReversal,
    updateTargetPrice,
    updateAlert,
    handleWatchlistUpsert,
    handleWatchlistDelete,
    cancelReview,
    switchPortfolio,
    exitOverview,
  } = actions

  const {
    setResearchTarget,
    setResearchResults,
    setReviewForm,
    setReviewingEvent,
    setAnalystReports,
    setReportRefreshMeta,
    setNewsEvents,
    setStrategyBrain,
    setBrainValidation,
    setDailyReport,
    setAnalysisHistory,
    setHoldings,
    setLastUpdate,
    setTradeLog,
    setResearchHistory,
    setPortfolios,
    setActivePortfolioId,
    setViewMode,
    setCloudSync,
    setShowReversal,
    setScanQuery,
    setScanFilter,
    setSortBy,
    setExpandedStock,
    setRelayPlanExpanded,
    setFilterType,
    setCatalystFilter,
    setDailyExpanded,
    setTab,
    setExpandedNews,
  } = setters

  const { defaultNewsEvents, researchResults, stockMeta, indColor } = resources
  const { flashSaved, requestAppConfirmation } = runtime
  const {
    priceSelfHealRef,
    syncPostClosePrices,
    refreshAnalystReportsRef,
    resetTradeCaptureRef,
    applyPortfolioSnapshot,
    portfolioTransitionRef,
    cloudSyncStateRef,
    livePortfolioSnapshot,
  } = refs

  const {
    formatEventStockOutcomeLine,
    isClosedEvent,
    resolveHoldingPrice,
    getHoldingUnrealizedPnl,
    getHoldingReturnPct,
    getMarketQuotesForCodes,
    buildDailyHoldingDossierContext,
    formatPortfolioNotesContext,
    formatBrainChecklistsForPrompt,
    formatBrainRulesForValidationPrompt,
    normalizeStrategyBrain,
    createEmptyBrainAudit,
    ensureBrainAuditCoverage,
    enforceTaiwanHardGatesOnBrainAudit,
    mergeBrainWithAuditLifecycle,
    appendBrainValidationCases,
    normalizeHoldings,
    applyTradeEntryToHoldings,
    createDefaultFundamentalDraft,
    toSlashDate,
    createDefaultReviewForm,
  } = helpers

  const reportRuntime = useAppReportRuntime({
    reportArgs: {
      activePortfolioId,
      holdings: H,
      dossierByCode,
      analystReports,
      reportRefreshMeta,
      reportRefreshCandidates,
      todayRefreshKey,
      upsertTargetReport,
      upsertFundamentalsEntry,
      setAnalystReports,
      setReportRefreshMeta,
      flashSaved,
      toSlashDate,
    },
    postCloseSyncArgs: {
      ready,
      viewMode,
      portfolioViewMode,
      shouldTriggerPostCloseSelfHeal,
      activePortfolioId,
      todayMarketClock,
      priceSelfHealRef,
      syncPostClosePrices,
    },
    researchAutoRefreshArgs: {
      ready,
      viewMode,
      portfolioViewMode,
      tab,
      reportRefreshMeta,
      todayRefreshKey,
      reportRefreshCandidates,
      refreshAnalystReportsRef,
    },
  })

  const {
    reportRefreshing,
    reportRefreshStatus,
    enrichingResearchCode,
    refreshAnalystReports,
    enrichResearchToDossier,
  } = reportRuntime

  const resolvedNewsEvents = resolveRuntimeNewsEvents(newsEvents, defaultNewsEvents)
  const filteredEvents = filterEventsByType({
    newsEvents,
    fallbackEvents: defaultNewsEvents,
    filterType,
    allFilterLabel: APP_LABELS.allFilter,
  }).filter((event) => catalystFilter === '全部' || event.catalystType === catalystFilter)

  const panelHoldingDossiers = useMemo(() => Array.from(dossierByCode.values()), [dossierByCode])

  const { runDailyAnalysis, maybeAutoConfirmDailyReport } = useAppDailyAnalysisRuntime(
    {
      analyzing,
      setAnalyzing,
      setAnalyzeStep,
      holdings: H,
      losers,
      newsEvents,
      defaultNewsEvents,
      analysisHistory,
      strategyBrain,
      portfolioNotes,
      reversalConditions,
      reportRefreshMeta,
      todayRefreshKey,
      dossierByCode,
      activePortfolioId,
      canUseCloud,
      getMarketQuotesForCodes,
      resolveHoldingPrice,
      getHoldingUnrealizedPnl,
      getHoldingReturnPct,
      buildDailyHoldingDossierContext,
      formatPortfolioNotesContext,
      formatBrainChecklistsForPrompt,
      formatBrainRulesForValidationPrompt,
      normalizeStrategyBrain,
      createEmptyBrainAudit,
      ensureBrainAuditCoverage,
      enforceTaiwanHardGatesOnBrainAudit,
      mergeBrainWithAuditLifecycle,
      appendBrainValidationCases,
      normalizeHoldings,
      isClosedEvent,
      toSlashDate,
      setDailyReport,
      setAnalysisHistory,
      setStrategyBrain,
      setBrainValidation,
      setHoldings,
      setLastUpdate,
      flashSaved,
    },
    refreshAnalystReportsRef
  )

  const { stressTesting, stressResult, setStressResult, runStressTest } = useAppStressTestRuntime({
    analyzing,
    setAnalyzeStep,
    workflowArgs: {
      holdings: H,
      dossierByCode,
      getMarketQuotesForCodes,
      resolveHoldingPrice,
      getHoldingUnrealizedPnl,
      getHoldingReturnPct,
      buildDailyHoldingDossierContext,
      toSlashDate,
    },
  })

  const { submitReview } = useAppEventReviewRuntime({
    newsEvents,
    defaultNewsEvents,
    reviewForm,
    setNewsEvents,
    setReviewingEvent,
    setReviewForm,
    flashSaved,
    activePortfolioId,
    portfolios,
    strategyBrain,
    portfolioNotes,
    dossierByCode,
    setStrategyBrain,
    setBrainValidation,
    toSlashDate,
  })

  const { copyWeeklyReport } = useAppWeeklyReportRuntime({
    activePortfolioId,
    portfolios,
    holdings: H,
    watchlist: W,
    analysisHistory,
    newsEvents: resolvedNewsEvents,
    strategyBrain,
    totalCost,
    totalVal,
    totalPnl,
    retPct,
    isClosedEvent,
    resolveHoldingPrice,
    getHoldingUnrealizedPnl,
    getHoldingReturnPct,
    brainRuleSummary,
    flashSaved,
  })

  const tradeCapture = useAppTradeRuntime({
    workflowArgs: {
      holdings,
      tradeLog,
      marketQuotes: marketPriceCache?.prices,
      setHoldings,
      setTradeLog,
      upsertTargetReport,
      upsertFundamentalsEntry,
      applyTradeEntryToHoldings,
      createDefaultFundamentalDraft,
      toSlashDate,
      flashSaved,
      setTab,
    },
    refreshAnalystReportsRef,
    refreshAnalystReports,
    resetTradeCaptureRef,
  })

  const {
    runResearch,
    applyBrainProposal,
    discardBrainProposal,
    proposalActionId,
    proposalActionType,
  } = useAppResearchRuntime({
    researching,
    setResearching,
    setResearchTarget,
    activePortfolioId,
    holdings: H,
    dossierByCode,
    stockMeta,
    strategyBrain,
    portfolioNotes,
    canUseCloud,
    newsEvents,
    analysisHistory,
    resolveHoldingPrice,
    getHoldingUnrealizedPnl,
    getHoldingReturnPct,
    setResearchResults,
    setResearchHistory,
    setStrategyBrain,
    flashSaved,
    enrichResearchToDossier,
  })

  const { backupFileInputRef, exportLocalBackup, importLocalBackup } = useAppLocalBackupRuntime({
    workflowArgs: {
      portfolios,
      activePortfolioId,
      viewMode,
      marketQuotes: marketPriceCache?.prices,
      requestAppConfirmation,
      applyPortfolioSnapshot,
      setPortfolios,
      setActivePortfolioId,
      setViewMode,
      setCloudSync,
      flashSaved,
    },
    portfolioTransitionRef,
    cloudSyncStateRef,
    livePortfolioSnapshot,
  })

  const { portfolioPanelsData, portfolioPanelsActions } = useAppPanelsRuntime({
    data: {
      ready,
      activePortfolioId,
      overviewPortfolios,
      overviewTotalValue,
      overviewTotalPnl,
      overviewDuplicateHoldings,
      overviewPendingItems,
      holdings,
      watchlist: W,
      holdingDossiers: panelHoldingDossiers,
      totalVal,
      totalCost,
      todayTotalPnl,
      urgentCount,
      todayAlertSummary,
      winners,
      losers,
      top5,
      holdingsIntegrityIssues,
      filteredEvents,
      morningNote,
      dailySnapshotStatus,
      dailyReport,
      newsEvents,
      strategyBrain,
      reportRefreshMeta,
      dataRefreshRows,
      researchHistory,
      tradeLog,
      renderViewMode,
    },
    ui: {
      showReversal,
      reversalConditions,
      reviewingEvent,
      attentionCount,
      pendingCount,
      targetUpdateCount,
      scanQuery,
      scanFilter,
      sortBy,
      expandedStock,
      watchlistFocus,
      watchlistRows,
      showRelayPlan,
      relayPlanExpanded,
      filterType,
      catalystFilter,
      dailyExpanded,
      researchTarget,
      reviewForm,
      expandedNews,
    },
    asyncState: {
      analyzing,
      analyzeStep,
      stressResult,
      stressTesting,
      researching,
      reportRefreshing,
      reportRefreshStatus,
      enrichingResearchCode,
      proposalActionId,
      proposalActionType,
    },
    resources: {
      researchResults,
      stockMeta,
      indColor,
      tradeCapture,
      createDefaultReviewForm,
    },
    controls: {
      exitOverview,
      switchPortfolio,
      setShowReversal,
      setReviewingEvent,
      updateReversal,
      setScanQuery,
      setScanFilter,
      setSortBy,
      setExpandedStock,
      setRelayPlanExpanded,
      setFilterType,
      setCatalystFilter,
      setDailyExpanded,
      setStressResult,
      setTab,
      setExpandedNews,
      setResearchResults,
      setReviewForm,
    },
    actions: {
      updateTargetPrice,
      updateAlert,
      handleWatchlistUpsert,
      handleWatchlistDelete,
      formatEventStockOutcomeLine,
      runDailyAnalysis,
      maybeAutoConfirmDailyReport,
      runStressTest,
      refreshAnalystReports,
      runResearch,
      enrichResearchToDossier,
      applyBrainProposal,
      discardBrainProposal,
      submitReview,
      cancelReview,
    },
  })

  return {
    copyWeeklyReport,
    backupFileInputRef,
    exportLocalBackup,
    importLocalBackup,
    portfolioPanelsData,
    portfolioPanelsActions,
  }
}
