import { OWNER_PORTFOLIO_ID, PORTFOLIO_VIEW_MODE } from '../constants.js'

export function useAppBootRuntimeComposer({
  holdings,
  watchlist,
  newsEvents,
  portfoliosRef,
  activePortfolioIdRef,
  viewModeRef,
  setHoldings,
  flashSaved,
  requestAppConfirmation,
  ready,
  marketPriceCache,
  cloudSyncStateRef,
  portfolioSetterRef,
  setCloudSync,
  tradeLog,
  targets,
  fundamentals,
  analystReports,
  reportRefreshMeta,
  holdingDossiers,
  analysisHistory,
  dailyReport,
  reversalConditions,
  strategyBrain,
  researchHistory,
  portfolioNotes,
  setTradeLog,
  setTargets,
  setFundamentals,
  setWatchlist,
  setAnalystReports,
  setReportRefreshMeta,
  setHoldingDossiers,
  setNewsEvents,
  setAnalysisHistory,
  setReversalConditions,
  setStrategyBrain,
  setBrainValidation,
  setResearchHistory,
  setPortfolioNotes,
  setDailyReport,
  normalizeAnalysisHistoryEntries,
  applyMarketQuotesToHoldings,
  normalizeFundamentalsStore,
  normalizeWatchlist,
  normalizeAnalystReportsStore,
  normalizeReportRefreshMeta,
  normalizeHoldingDossiers,
  normalizeNewsEvents,
  normalizeStrategyBrain,
  normalizeBrainValidationStore,
  normalizeDailyReportEntry,
  clonePortfolioNotes,
  loadPortfolioSnapshot,
  readSyncAt,
  save,
  savePortfolioData,
}) {
  return {
    marketDataArgs: {
      holdings,
      watchlist,
      newsEvents,
      portfoliosRef,
      activePortfolioIdRef,
      viewModeRef,
      setHoldings,
      notifySaved: flashSaved,
      requestConfirmation: requestAppConfirmation,
    },
    portfolioSnapshotArgs: {
      ready,
      marketPriceCache,
      cloudSyncStateRef,
      portfolioSetterRef,
      setCloudSync,
      holdings,
      tradeLog,
      targets,
      fundamentals,
      watchlist,
      analystReports,
      reportRefreshMeta,
      holdingDossiers,
      newsEvents,
      analysisHistory,
      dailyReport,
      reversalConditions,
      strategyBrain,
      researchHistory,
      portfolioNotes,
      setHoldings,
      setTradeLog,
      setTargets,
      setFundamentals,
      setWatchlist,
      setAnalystReports,
      setReportRefreshMeta,
      setHoldingDossiers,
      setNewsEvents,
      setAnalysisHistory,
      setReversalConditions,
      setStrategyBrain,
      setBrainValidation,
      setResearchHistory,
      setPortfolioNotes,
      setDailyReport,
      normalizeAnalysisHistoryEntries,
      applyMarketQuotesToHoldings,
      normalizeFundamentalsStore,
      normalizeWatchlist,
      normalizeAnalystReportsStore,
      normalizeReportRefreshMeta,
      normalizeHoldingDossiers,
      normalizeNewsEvents,
      normalizeStrategyBrain,
      normalizeBrainValidationStore,
      normalizeDailyReportEntry,
      clonePortfolioNotes,
      loadPortfolioSnapshot,
      readSyncAt,
      save,
      savePortfolioData,
    },
  }
}

export function usePortfolioManagementComposer({
  ready,
  ownerPortfolioId = OWNER_PORTFOLIO_ID,
  portfolioViewMode = PORTFOLIO_VIEW_MODE,
  holdings,
  newsEvents,
  portfolioNotes,
  marketPriceCache,
  flushCurrentPortfolio,
  restoreTabForPortfolio,
  resetTransientUiState,
  loadPortfolio,
  flashSaved,
}) {
  return {
    ready,
    initialPortfolios: [],
    initialActivePortfolioId: ownerPortfolioId,
    initialViewMode: portfolioViewMode,
    activeHoldings: holdings,
    activeNewsEvents: newsEvents,
    activePortfolioNotes: portfolioNotes,
    marketPriceCache,
    flushCurrentPortfolio,
    restoreTabForPortfolio,
    resetTransientUiState,
    loadPortfolio,
    notifySaved: flashSaved,
  }
}

export function useAppLifecycleRuntimeComposer({
  ready,
  ownerPortfolioId = OWNER_PORTFOLIO_ID,
  portfolioViewMode = PORTFOLIO_VIEW_MODE,
  activePortfolioId,
  viewMode,
  portfolioSwitching,
  portfolios,
  setPortfolios,
  setActivePortfolioId,
  setViewMode,
  activePortfolioIdRef,
  viewModeRef,
  portfoliosRef,
  portfolioSetterRef,
  bootRuntimeRef,
  marketPriceCache,
  marketPriceSync,
  restoreTabForPortfolio,
  holdings,
  tradeLog,
  targets,
  fundamentals,
  watchlist,
  analystReports,
  reportRefreshMeta,
  holdingDossiers,
  newsEvents,
  analysisHistory,
  dailyReport,
  reversalConditions,
  strategyBrain,
  brainValidation,
  researchHistory,
  portfolioNotes,
  tab,
  cloudSyncStateRef,
  cloudSaveTimersRef,
  applyPortfolioSnapshot,
  portfolioTransitionRef,
  setReady,
  setBootstrapState,
  setCloudSync,
  setHoldings,
  setTargets,
  setFundamentals,
  setWatchlist,
  setHoldingDossiers,
  setAnalysisHistory,
  setReversalConditions,
  setStrategyBrain,
  setNewsEvents,
  setDailyReport,
  setResearchHistory,
  setReviewingEvent,
  setReviewForm,
  flashSaved,
  createDefaultReviewForm,
  migrateLegacyPortfolioStorageIfNeeded,
  seedJinlianchengIfNeeded,
  ensurePortfolioRegistry,
  applyTradeBackfillPatchesIfNeeded,
  loadPortfolioSnapshot,
  readSyncAt,
  writeSyncAt,
  shouldAdoptCloudHoldings,
  normalizeHoldings,
  buildHoldingPriceHints,
  getPortfolioFallback,
  savePortfolioData,
  buildHoldingDossiers,
  applyMarketQuotesToHoldings,
  normalizeHoldingDossiers,
  normalizeAnalysisHistoryEntries,
  normalizeStrategyBrain,
  normalizeNewsEvents,
  normalizeDailyReportEntry,
  toSlashDate,
  getMarketQuotesForCodes,
  getEventStockCodes,
  parseSlashDate,
  appendPriceHistory,
}) {
  const canPersistPortfolioData = ready && viewMode === portfolioViewMode && !portfolioSwitching
  const canUseCloud = viewMode === portfolioViewMode && activePortfolioId === ownerPortfolioId

  return {
    canUseCloud,
    runtimeSyncRefsArgs: {
      activePortfolioIdRef,
      activePortfolioId,
      viewModeRef,
      viewMode,
      portfoliosRef,
      portfolios,
      portfolioSetterRef,
      setActivePortfolioId,
      setViewMode,
      bootRuntimeRef,
      marketPriceCache,
      applyPortfolioSnapshot,
      setPortfolios,
      portfolioTransitionRef,
    },
    portfolioBootstrapArgs: {
      bootRuntimeRef,
      setReady,
      setBootstrapState,
      setCloudSync,
      cloudSyncStateRef,
      setHoldings,
      setStrategyBrain,
      setNewsEvents,
      setAnalysisHistory,
      setDailyReport,
      setResearchHistory,
      restoreTabForPortfolio,
      migrateLegacyPortfolioStorageIfNeeded,
      seedJinlianchengIfNeeded,
      ensurePortfolioRegistry,
      applyTradeBackfillPatchesIfNeeded,
      loadPortfolioSnapshot,
      readSyncAt,
      writeSyncAt,
      shouldAdoptCloudHoldings,
      normalizeHoldings,
      buildHoldingPriceHints,
      getPortfolioFallback,
      savePortfolioData,
      normalizeStrategyBrain,
      normalizeNewsEvents,
      normalizeAnalysisHistoryEntries,
      normalizeDailyReportEntry,
    },
    portfolioPersistenceArgs: {
      activePortfolioId,
      canPersistPortfolioData,
      canUseCloud,
      tab,
      holdings,
      tradeLog,
      targets,
      fundamentals,
      watchlist,
      analystReports,
      reportRefreshMeta,
      holdingDossiers,
      newsEvents,
      analysisHistory,
      dailyReport,
      reversalConditions,
      strategyBrain,
      brainValidation,
      researchHistory,
      portfolioNotes,
      marketPriceCache,
      marketPriceSync,
      setHoldingDossiers,
      setAnalysisHistory,
      setResearchHistory,
      notifySaved: flashSaved,
      cloudSyncStateRef,
      cloudSaveTimersRef,
      normalizeHoldings,
      savePortfolioData,
      buildHoldingDossiers,
      applyMarketQuotesToHoldings,
      normalizeHoldingDossiers,
      normalizeAnalysisHistoryEntries,
      readSyncAt,
      writeSyncAt,
    },
    dossierActionArgs: {
      marketQuotes: marketPriceCache?.prices || null,
      setHoldings,
      setTargets,
      setFundamentals,
      flashSaved,
      toSlashDate,
    },
    watchlistActionsArgs: {
      setWatchlist,
    },
    transientUiArgs: {
      setReversalConditions,
      flashSaved,
      toSlashDate,
      setReviewingEvent,
      setReviewForm,
      createDefaultReviewForm,
    },
    eventLifecycleArgs: {
      activePortfolioId,
      ready,
      viewMode,
      newsEvents,
      setNewsEvents,
      portfolioTransitionRef,
      getMarketQuotesForCodes,
      normalizeNewsEvents,
      getEventStockCodes,
      parseSlashDate,
      toSlashDate,
      appendPriceHistory,
    },
  }
}
