import { OWNER_PORTFOLIO_ID, PORTFOLIO_VIEW_MODE } from '../constants.js'

export function useAppBootRuntimeComposer({
  holdings,
  watchlist,
  newsEvents,
  portfoliosRef,
  activePortfolioIdRef,
  viewModeRef,
  setHoldings,
  flashSaved,
  requestAppConfirmation,
  ready,
  marketPriceCache,
  cloudSyncStateRef,
  portfolioSetterRef,
  setCloudSync,
  tradeLog,
  targets,
  fundamentals,
  analystReports,
  reportRefreshMeta,
  holdingDossiers,
  analysisHistory,
  dailyReport,
  reversalConditions,
  strategyBrain,
  researchHistory,
  portfolioNotes,
  setTradeLog,
  setTargets,
  setFundamentals,
  setWatchlist,
  setAnalystReports,
  setReportRefreshMeta,
  setHoldingDossiers,
  setNewsEvents,
  setAnalysisHistory,
  setReversalConditions,
  setStrategyBrain,
  setBrainValidation,
  setResearchHistory,
  setPortfolioNotes,
  setDailyReport,
  normalizeAnalysisHistoryEntries,
  applyMarketQuotesToHoldings,
  normalizeFundamentalsStore,
  normalizeWatchlist,
  normalizeAnalystReportsStore,
  normalizeReportRefreshMeta,
  normalizeHoldingDossiers,
  normalizeNewsEvents,
  normalizeStrategyBrain,
  normalizeBrainValidationStore,
  normalizeDailyReportEntry,
  clonePortfolioNotes,
  loadPortfolioSnapshot,
  readSyncAt,
  save,
  savePortfolioData,
}) {
  return {
    marketDataArgs: {
      holdings,
      watchlist,
      newsEvents,
      portfoliosRef,
      activePortfolioIdRef,
      viewModeRef,
      setHoldings,
      notifySaved: flashSaved,
      requestConfirmation: requestAppConfirmation,
    },
    portfolioSnapshotArgs: {
      ready,
      marketPriceCache,
      cloudSyncStateRef,
      portfolioSetterRef,
      setCloudSync,
      holdings,
      tradeLog,
      targets,
      fundamentals,
      watchlist,
      analystReports,
      reportRefreshMeta,
      holdingDossiers,
      newsEvents,
      analysisHistory,
      dailyReport,
      reversalConditions,
      strategyBrain,
      researchHistory,
      portfolioNotes,
      setHoldings,
      setTradeLog,
      setTargets,
      setFundamentals,
      setWatchlist,
      setAnalystReports,
      setReportRefreshMeta,
      setHoldingDossiers,
      setNewsEvents,
      setAnalysisHistory,
      setReversalConditions,
      setStrategyBrain,
      setBrainValidation,
      setResearchHistory,
      setPortfolioNotes,
      setDailyReport,
      normalizeAnalysisHistoryEntries,
      applyMarketQuotesToHoldings,
      normalizeFundamentalsStore,
      normalizeWatchlist,
      normalizeAnalystReportsStore,
      normalizeReportRefreshMeta,
      normalizeHoldingDossiers,
      normalizeNewsEvents,
      normalizeStrategyBrain,
      normalizeBrainValidationStore,
      normalizeDailyReportEntry,
      clonePortfolioNotes,
      loadPortfolioSnapshot,
      readSyncAt,
      save,
      savePortfolioData,
    },
  }
}

export function usePortfolioManagementComposer({
  ready,
  ownerPortfolioId = OWNER_PORTFOLIO_ID,
  portfolioViewMode = PORTFOLIO_VIEW_MODE,
  holdings,
  newsEvents,
  portfolioNotes,
  marketPriceCache,
  flushCurrentPortfolio,
  resetTransientUiState,
  loadPortfolio,
  flashSaved,
}) {
  return {
    ready,
    initialPortfolios: [],
    initialActivePortfolioId: ownerPortfolioId,
    initialViewMode: portfolioViewMode,
    activeHoldings: holdings,
    activeNewsEvents: newsEvents,
    activePortfolioNotes: portfolioNotes,
    marketPriceCache,
    flushCurrentPortfolio,
    resetTransientUiState,
    loadPortfolio,
    notifySaved: flashSaved,
  }
}

export function useAppLifecycleRuntimeComposer({
  ready,
  ownerPortfolioId = OWNER_PORTFOLIO_ID,
  portfolioViewMode = PORTFOLIO_VIEW_MODE,
  activePortfolioId,
  viewMode,
  portfolioSwitching,
  portfolios,
  setPortfolios,
  setActivePortfolioId,
  setViewMode,
  activePortfolioIdRef,
  viewModeRef,
  portfoliosRef,
  portfolioSetterRef,
  bootRuntimeRef,
  marketPriceCache,
  marketPriceSync,
  holdings,
  tradeLog,
  targets,
  fundamentals,
  watchlist,
  analystReports,
  reportRefreshMeta,
  holdingDossiers,
  newsEvents,
  analysisHistory,
  dailyReport,
  reversalConditions,
  strategyBrain,
  brainValidation,
  researchHistory,
  portfolioNotes,
  tab,
  cloudSyncStateRef,
  cloudSaveTimersRef,
  applyPortfolioSnapshot,
  portfolioTransitionRef,
  setReady,
  setBootstrapState,
  setCloudSync,
  setHoldings,
  setTargets,
  setFundamentals,
  setWatchlist,
  setHoldingDossiers,
  setAnalysisHistory,
  setReversalConditions,
  setStrategyBrain,
  setNewsEvents,
  setDailyReport,
  setResearchHistory,
  setReviewingEvent,
  setReviewForm,
  flashSaved,
  createDefaultReviewForm,
  migrateLegacyPortfolioStorageIfNeeded,
  seedJinlianchengIfNeeded,
  ensurePortfolioRegistry,
  applyTradeBackfillPatchesIfNeeded,
  loadPortfolioSnapshot,
  readSyncAt,
  writeSyncAt,
  shouldAdoptCloudHoldings,
  normalizeHoldings,
  buildHoldingPriceHints,
  getPortfolioFallback,
  savePortfolioData,
  buildHoldingDossiers,
  applyMarketQuotesToHoldings,
  normalizeHoldingDossiers,
  normalizeAnalysisHistoryEntries,
  normalizeStrategyBrain,
  normalizeNewsEvents,
  normalizeDailyReportEntry,
  toSlashDate,
  getMarketQuotesForCodes,
  getEventStockCodes,
  parseSlashDate,
  appendPriceHistory,
}) {
  const canPersistPortfolioData = ready && viewMode === portfolioViewMode && !portfolioSwitching
  const canUseCloud = viewMode === portfolioViewMode && activePortfolioId === ownerPortfolioId

  return {
    canUseCloud,
    runtimeSyncRefsArgs: {
      activePortfolioIdRef,
      activePortfolioId,
      viewModeRef,
      viewMode,
      portfoliosRef,
      portfolios,
      portfolioSetterRef,
      setActivePortfolioId,
      setViewMode,
      bootRuntimeRef,
      marketPriceCache,
      applyPortfolioSnapshot,
      setPortfolios,
      portfolioTransitionRef,
    },
    portfolioBootstrapArgs: {
      bootRuntimeRef,
      setReady,
      setBootstrapState,
      setCloudSync,
      cloudSyncStateRef,
      setHoldings,
      setStrategyBrain,
      setNewsEvents,
      setAnalysisHistory,
      setDailyReport,
      setResearchHistory,
      migrateLegacyPortfolioStorageIfNeeded,
      seedJinlianchengIfNeeded,
      ensurePortfolioRegistry,
      applyTradeBackfillPatchesIfNeeded,
      loadPortfolioSnapshot,
      readSyncAt,
      writeSyncAt,
      shouldAdoptCloudHoldings,
      normalizeHoldings,
      buildHoldingPriceHints,
      getPortfolioFallback,
      savePortfolioData,
      normalizeStrategyBrain,
      normalizeNewsEvents,
      normalizeAnalysisHistoryEntries,
      normalizeDailyReportEntry,
    },
    portfolioPersistenceArgs: {
      activePortfolioId,
      canPersistPortfolioData,
      canUseCloud,
      tab,
      holdings,
      tradeLog,
      targets,
      fundamentals,
      watchlist,
      analystReports,
      reportRefreshMeta,
      holdingDossiers,
      newsEvents,
      analysisHistory,
      dailyReport,
      reversalConditions,
      strategyBrain,
      brainValidation,
      researchHistory,
      portfolioNotes,
      marketPriceCache,
      marketPriceSync,
      setHoldingDossiers,
      setAnalysisHistory,
      setResearchHistory,
      notifySaved: flashSaved,
      cloudSyncStateRef,
      cloudSaveTimersRef,
      normalizeHoldings,
      savePortfolioData,
      buildHoldingDossiers,
      applyMarketQuotesToHoldings,
      normalizeHoldingDossiers,
      normalizeAnalysisHistoryEntries,
      readSyncAt,
      writeSyncAt,
    },
    dossierActionArgs: {
      marketQuotes: marketPriceCache?.prices || null,
      setHoldings,
      setTargets,
      setFundamentals,
      flashSaved,
      toSlashDate,
    },
    watchlistActionsArgs: {
      setWatchlist,
    },
    transientUiArgs: {
      setReversalConditions,
      flashSaved,
      toSlashDate,
      setReviewingEvent,
      setReviewForm,
      createDefaultReviewForm,
    },
    eventLifecycleArgs: {
      activePortfolioId,
      ready,
      viewMode,
      tab,
      newsEvents,
      setNewsEvents,
      portfolioTransitionRef,
      getMarketQuotesForCodes,
      normalizeNewsEvents,
      getEventStockCodes,
      parseSlashDate,
      toSlashDate,
      appendPriceHistory,
    },
  }
}

export function composeAppRuntimeCoreLifecycleArgs({ data, refs, setters, ui, runtime, helpers }) {
  return {
    ...data,
    ...refs,
    ...setters,
    ...ui,
    ...runtime,
    helpers,
  }
}

export function composeAppRuntimeWorkflowsArgs({
  data,
  ui,
  asyncState,
  actions,
  setters,
  resources,
  refs,
  runtime,
  helpers,
}) {
  return {
    ...data,
    ...ui,
    ...asyncState,
    ...actions,
    ...setters,
    ...resources,
    ...refs,
    ...runtime,
    helpers,
  }
}

export function composeAppRuntimeWorkflowInput({
  runtimeState,
  runtimeSetters,
  coreLifecycle,
  portfolioDerived,
  uiState,
  asyncState,
  runtime,
  helpers,
  resources,
  refs,
  portfolioViewMode = PORTFOLIO_VIEW_MODE,
}) {
  return {
    state: {
      ...runtimeState,
      viewMode: coreLifecycle.viewMode,
      portfolioViewMode,
      activePortfolioId: coreLifecycle.activePortfolioId,
      canUseCloud: coreLifecycle.canUseCloud,
      marketPriceCache: coreLifecycle.marketPriceCache,
      portfolios: coreLifecycle.portfolios,
      morningNote: resources.morningNote,
    },
    derived: portfolioDerived,
    ui: {
      tab: uiState.tab,
      filterType: uiState.filterType,
      catalystFilter: uiState.catalystFilter,
      scanQuery: uiState.scanQuery,
      scanFilter: uiState.scanFilter,
      sortBy: uiState.sortBy,
      showReversal: uiState.showReversal,
      expandedStock: uiState.expandedStock,
      relayPlanExpanded: uiState.relayPlanExpanded,
      dailyExpanded: uiState.dailyExpanded,
      researchTarget: uiState.researchTarget,
      reviewForm: uiState.reviewForm,
      reviewingEvent: uiState.reviewingEvent,
      expandedNews: uiState.expandedNews,
    },
    asyncState,
    actions: {
      upsertTargetReport: coreLifecycle.upsertTargetReport,
      upsertFundamentalsEntry: coreLifecycle.upsertFundamentalsEntry,
      updateReversal: coreLifecycle.updateReversal,
      updateTargetPrice: coreLifecycle.updateTargetPrice,
      updateAlert: coreLifecycle.updateAlert,
      handleWatchlistUpsert: coreLifecycle.handleWatchlistUpsert,
      handleWatchlistDelete: coreLifecycle.handleWatchlistDelete,
      cancelReview: coreLifecycle.cancelReview,
      switchPortfolio: coreLifecycle.switchPortfolio,
      exitOverview: coreLifecycle.exitOverview,
    },
    setters: {
      ...runtimeSetters,
      setLastUpdate: coreLifecycle.setLastUpdate,
      setPortfolios: coreLifecycle.setPortfolios,
      setActivePortfolioId: coreLifecycle.setActivePortfolioId,
      setViewMode: coreLifecycle.setViewMode,
      setShowReversal: uiState.setShowReversal,
      setScanQuery: uiState.setScanQuery,
      setScanFilter: uiState.setScanFilter,
      setSortBy: uiState.setSortBy,
      setExpandedStock: uiState.setExpandedStock,
      setRelayPlanExpanded: uiState.setRelayPlanExpanded,
      setFilterType: uiState.setFilterType,
      setCatalystFilter: uiState.setCatalystFilter,
      setDailyExpanded: uiState.setDailyExpanded,
      setTab: uiState.setTab,
      setExpandedNews: uiState.setExpandedNews,
      setResearchTarget: uiState.setResearchTarget,
      setResearchResults: uiState.setResearchResults,
      setReviewForm: uiState.setReviewForm,
      setReviewingEvent: uiState.setReviewingEvent,
    },
    resources: {
      defaultNewsEvents: resources.defaultNewsEvents,
      researchResults: uiState.researchResults,
      stockMeta: resources.stockMeta,
      indColor: resources.indColor,
    },
    runtime,
    refs,
    helpers: {
      ...helpers,
      getMarketQuotesForCodes: coreLifecycle.getMarketQuotesForCodes,
    },
  }
}

export function composeAppRuntimeHeaderInput({
  theme,
  sync,
  coreLifecycle,
  portfolioDerived,
  notes,
  asyncState,
  tabs,
  constants,
  ready,
}) {
  return {
    theme: {
      C: theme.C,
      pc: theme.pc,
    },
    sync: {
      cloudSync: sync.cloudSync,
      saved: sync.saved,
      refreshPrices: coreLifecycle.refreshPrices,
      refreshing: coreLifecycle.refreshing,
      copyWeeklyReport: sync.copyWeeklyReport,
      exportLocalBackup: sync.exportLocalBackup,
      backupFileInputRef: sync.backupFileInputRef,
      importLocalBackup: sync.importLocalBackup,
      priceSyncStatusTone: coreLifecycle.priceSyncStatusTone,
      priceSyncStatusLabel: coreLifecycle.priceSyncStatusLabel,
      activePriceSyncAt: coreLifecycle.activePriceSyncAt,
      lastUpdate: coreLifecycle.lastUpdate,
    },
    pnl: {
      displayedTotalPnl: portfolioDerived.displayedTotalPnl,
      displayedRetPct: portfolioDerived.displayedRetPct,
    },
    portfolio: {
      activePortfolioId: coreLifecycle.activePortfolioId,
      switchPortfolio: coreLifecycle.switchPortfolio,
      ready,
      portfolioSwitching: coreLifecycle.portfolioSwitching,
      portfolioSummaries: coreLifecycle.portfolioSummaries,
      createPortfolio: coreLifecycle.createPortfolio,
      viewMode: coreLifecycle.viewMode,
      exitOverview: coreLifecycle.exitOverview,
      openOverview: coreLifecycle.openOverview,
      showPortfolioManager: coreLifecycle.showPortfolioManager,
      setShowPortfolioManager: coreLifecycle.setShowPortfolioManager,
      renamePortfolio: coreLifecycle.renamePortfolio,
      deletePortfolio: coreLifecycle.deletePortfolio,
    },
    overview: {
      overviewTotalValue: portfolioDerived.overviewTotalValue,
    },
    notes,
    tabs: {
      urgentCount: portfolioDerived.urgentCount,
      todayAlertSummary: portfolioDerived.todayAlertSummary,
      analyzing: asyncState.analyzing,
      researching: asyncState.researching,
      tab: tabs.tab,
      setTab: tabs.setTab,
      workflowCue: tabs.workflowCue ?? null,
    },
    dialogs: {
      portfolioEditor: coreLifecycle.portfolioEditor,
      portfolioDeleteDialog: coreLifecycle.portfolioDeleteDialog,
    },
    constants,
  }
}

export function pickPnlTone(value, colors) {
  if (value == null) return colors.textMute
  return value >= 0 ? colors.up : colors.down
}

export function buildFundamentalDraft(defaultDraft, overrides = {}) {
  return { ...defaultDraft, ...overrides }
}

export function composePortfolioDerivedDataInput({ data, helperFns, constants }) {
  return {
    holdings: data.holdings,
    watchlist: data.watchlist,
    sortBy: data.sortBy,
    holdingDossiers: data.holdingDossiers,
    targets: data.targets,
    fundamentals: data.fundamentals,
    analystReports: data.analystReports,
    newsEvents: data.newsEvents,
    researchHistory: data.researchHistory,
    strategyBrain: data.strategyBrain,
    marketPriceCache: data.marketPriceCache,
    marketPriceSync: data.marketPriceSync,
    activePortfolioId: data.activePortfolioId,
    portfolioSummaries: data.portfolioSummaries,
    viewMode: data.viewMode,
    portfolioNotes: data.portfolioNotes,
    reportRefreshMeta: data.reportRefreshMeta,
    helpers: {
      normalizeHoldingDossiers: helperFns.normalizeHoldingDossiers,
      buildHoldingDossiers: helperFns.buildHoldingDossiers,
      getHoldingMarketValue: helperFns.getHoldingMarketValue,
      getHoldingCostBasis: helperFns.getHoldingCostBasis,
      getHoldingUnrealizedPnl: helperFns.getHoldingUnrealizedPnl,
      getHoldingReturnPct: helperFns.getHoldingReturnPct,
      applyMarketQuotesToHoldings: helperFns.applyMarketQuotesToHoldings,
      clonePortfolioNotes: helperFns.clonePortfolioNotes,
      normalizeNewsEvents: helperFns.normalizeNewsEvents,
      getEventStockCodes: helperFns.getEventStockCodes,
      isClosedEvent: helperFns.isClosedEvent,
      parseFlexibleDate: helperFns.parseFlexibleDate,
      todayStorageDate: helperFns.todayStorageDate,
      formatDateToStorageDate: helperFns.formatDateToStorageDate,
      getTaipeiClock: helperFns.getTaipeiClock,
      parseStoredDate: helperFns.parseStoredDate,
      readStorageValue: helperFns.readStorageValue,
      pfKey: helperFns.pfKey,
      getPortfolioFallback: helperFns.getPortfolioFallback,
    },
    constants: {
      OWNER_PORTFOLIO_ID: constants.OWNER_PORTFOLIO_ID,
      PORTFOLIO_VIEW_MODE: constants.PORTFOLIO_VIEW_MODE,
      OVERVIEW_VIEW_MODE: constants.OVERVIEW_VIEW_MODE,
      POST_CLOSE_SYNC_MINUTES: constants.POST_CLOSE_SYNC_MINUTES,
      RELAY_PLAN_CODES: constants.RELAY_PLAN_CODES,
      STOCK_META: constants.STOCK_META,
      C: constants.C,
    },
  }
}

export function composeAppHeaderProps({
  theme,
  sync,
  pnl,
  portfolio,
  overview,
  notes,
  tabs,
  dialogs,
  constants,
}) {
  return {
    C: theme.C,
    pc: theme.pc,
    cloudSync: sync.cloudSync,
    saved: sync.saved,
    refreshPrices: sync.refreshPrices,
    refreshing: sync.refreshing,
    copyWeeklyReport: sync.copyWeeklyReport,
    exportLocalBackup: sync.exportLocalBackup,
    backupFileInputRef: sync.backupFileInputRef,
    importLocalBackup: sync.importLocalBackup,
    priceSyncStatusTone: sync.priceSyncStatusTone,
    priceSyncStatusLabel: sync.priceSyncStatusLabel,
    activePriceSyncAt: sync.activePriceSyncAt,
    lastUpdate: sync.lastUpdate,
    displayedTotalPnl: pnl.displayedTotalPnl,
    displayedRetPct: pnl.displayedRetPct,
    activePortfolioId: portfolio.activePortfolioId,
    switchPortfolio: portfolio.switchPortfolio,
    ready: portfolio.ready,
    portfolioSwitching: portfolio.portfolioSwitching,
    portfolioSummaries: portfolio.portfolioSummaries,
    createPortfolio: portfolio.createPortfolio,
    viewMode: portfolio.viewMode,
    exitOverview: portfolio.exitOverview,
    openOverview: portfolio.openOverview,
    showPortfolioManager: portfolio.showPortfolioManager,
    setShowPortfolioManager: portfolio.setShowPortfolioManager,
    renamePortfolio: portfolio.renamePortfolio,
    deletePortfolio: portfolio.deletePortfolio,
    OWNER_PORTFOLIO_ID: constants.OWNER_PORTFOLIO_ID,
    overviewTotalValue: overview.overviewTotalValue,
    portfolioNotes: notes.portfolioNotes,
    setPortfolioNotes: notes.setPortfolioNotes,
    PORTFOLIO_VIEW_MODE: constants.PORTFOLIO_VIEW_MODE,
    OVERVIEW_VIEW_MODE: constants.OVERVIEW_VIEW_MODE,
    urgentCount: tabs.urgentCount,
    todayAlertSummary: tabs.todayAlertSummary,
    TABS: tabs.portfolioTabs,
    tab: tabs.tab,
    setTab: tabs.setTab,
    workflowCue: tabs.workflowCue ?? null,
    portfolioEditor: dialogs.portfolioEditor,
    portfolioDeleteDialog: dialogs.portfolioDeleteDialog,
  }
}

export function composeAppShellFrameRuntime({
  ready,
  loadingMessage,
  loadingState,
  headerBoundaryCopy,
  headerProps,
  panelsData,
  panelsActions,
  panels,
  confirmDialog,
  closeAppConfirmDialog,
}) {
  return {
    ready,
    loadingMessage,
    loadingState,
    headerBoundaryCopy,
    headerProps,
    panelsData,
    panelsActions,
    panelsProps: {
      viewMode: panels.viewMode,
      overviewViewMode: panels.overviewViewMode,
      tab: panels.tab,
      errorBoundaryCopy: panels.errorBoundaryCopy,
    },
    confirmDialogProps: {
      open: confirmDialog.open,
      title: confirmDialog.title,
      message: confirmDialog.message,
      confirmLabel: confirmDialog.confirmLabel,
      cancelLabel: confirmDialog.cancelLabel,
      tone: confirmDialog.tone,
      onConfirm: () => closeAppConfirmDialog(true),
      onCancel: () => closeAppConfirmDialog(false),
    },
  }
}

export function composeReportRefreshWorkflowArgs({
  holdings,
  dossierByCode,
  analystReports,
  reportRefreshMeta,
  reportRefreshCandidates,
  todayRefreshKey,
  upsertTargetReport,
  upsertFundamentalsEntry,
  setAnalystReports,
  setReportRefreshMeta,
  flashSaved,
  toSlashDate,
}) {
  return {
    holdings,
    dossierByCode,
    analystReports,
    reportRefreshMeta,
    reportRefreshCandidates,
    todayRefreshKey,
    upsertTargetReport,
    upsertFundamentalsEntry,
    setAnalystReports,
    setReportRefreshMeta,
    flashSaved,
    toSlashDate,
  }
}

export function composeDailyAnalysisWorkflowArgs({
  analyzing,
  setAnalyzing,
  setAnalyzeStep,
  holdings,
  losers,
  newsEvents,
  defaultNewsEvents,
  analysisHistory,
  strategyBrain,
  portfolioNotes,
  reversalConditions,
  reportRefreshMeta,
  todayRefreshKey,
  dossierByCode,
  activePortfolioId,
  canUseCloud,
  getMarketQuotesForCodes,
  resolveHoldingPrice,
  getHoldingUnrealizedPnl,
  getHoldingReturnPct,
  buildDailyHoldingDossierContext,
  formatPortfolioNotesContext,
  formatBrainChecklistsForPrompt,
  formatBrainRulesForValidationPrompt,
  normalizeStrategyBrain,
  createEmptyBrainAudit,
  ensureBrainAuditCoverage,
  enforceTaiwanHardGatesOnBrainAudit,
  mergeBrainWithAuditLifecycle,
  appendBrainValidationCases,
  normalizeHoldings,
  isClosedEvent,
  toSlashDate,
  setDailyReport,
  setAnalysisHistory,
  setStrategyBrain,
  setBrainValidation,
  setHoldings,
  setLastUpdate,
  flashSaved,
}) {
  return {
    analyzing,
    setAnalyzing,
    setAnalyzeStep,
    holdings,
    losers,
    newsEvents,
    defaultNewsEvents,
    analysisHistory,
    strategyBrain,
    portfolioNotes,
    reversalConditions,
    reportRefreshMeta,
    todayRefreshKey,
    dossierByCode,
    activePortfolioId,
    canUseCloud,
    getMarketQuotesForCodes,
    resolveHoldingPrice,
    getHoldingUnrealizedPnl,
    getHoldingReturnPct,
    buildDailyHoldingDossierContext,
    formatPortfolioNotesContext,
    formatBrainChecklistsForPrompt,
    formatBrainRulesForValidationPrompt,
    normalizeStrategyBrain,
    createEmptyBrainAudit,
    ensureBrainAuditCoverage,
    enforceTaiwanHardGatesOnBrainAudit,
    mergeBrainWithAuditLifecycle,
    appendBrainValidationCases,
    normalizeHoldings,
    isClosedEvent,
    toSlashDate,
    setDailyReport,
    setAnalysisHistory,
    setStrategyBrain,
    setBrainValidation,
    setHoldings,
    setLastUpdate,
    notifySaved: flashSaved,
  }
}

export function composeStressTestWorkflowArgs({
  stressTesting,
  analyzing,
  setStressTesting,
  setAnalyzeStep,
  holdings,
  dossierByCode,
  getMarketQuotesForCodes,
  resolveHoldingPrice,
  getHoldingUnrealizedPnl,
  getHoldingReturnPct,
  buildDailyHoldingDossierContext,
  toSlashDate,
  setStressResult,
}) {
  return {
    stressTesting,
    analyzing,
    setStressTesting,
    setAnalyzeStep,
    holdings,
    dossierByCode,
    getMarketQuotesForCodes,
    resolveHoldingPrice,
    getHoldingUnrealizedPnl,
    getHoldingReturnPct,
    buildDailyHoldingDossierContext,
    toSlashDate,
    setStressResult,
  }
}

export function composeEventReviewWorkflowArgs({
  newsEvents,
  defaultNewsEvents,
  reviewForm,
  setNewsEvents,
  setReviewingEvent,
  setReviewForm,
  flashSaved,
  activePortfolioId,
  portfolios,
  strategyBrain,
  portfolioNotes,
  dossierByCode,
  setStrategyBrain,
  setBrainValidation,
  toSlashDate,
}) {
  return {
    newsEvents,
    defaultNewsEvents,
    reviewForm,
    setNewsEvents,
    setReviewingEvent,
    setReviewForm,
    flashSaved,
    activePortfolioId,
    portfolios,
    strategyBrain,
    portfolioNotes,
    dossierByCode,
    setStrategyBrain,
    setBrainValidation,
    toSlashDate,
  }
}

export function composeWeeklyReportClipboardArgs({
  holdings,
  watchlist,
  analysisHistory,
  newsEvents,
  strategyBrain,
  totalCost,
  totalVal,
  totalPnl,
  retPct,
  isClosedEvent,
  resolveHoldingPrice,
  getHoldingUnrealizedPnl,
  getHoldingReturnPct,
  brainRuleSummary,
  flashSaved,
}) {
  return {
    holdings,
    watchlist,
    analysisHistory,
    newsEvents,
    strategyBrain,
    totalCost,
    totalVal,
    totalPnl,
    retPct,
    isClosedEvent,
    resolveHoldingPrice,
    getHoldingUnrealizedPnl,
    getHoldingReturnPct,
    brainRuleSummary,
    flashSaved,
  }
}

export function composeTradeCaptureRuntimeArgs({
  holdings,
  tradeLog,
  marketQuotes,
  setHoldings,
  setTradeLog,
  upsertTargetReport,
  upsertFundamentalsEntry,
  applyTradeEntryToHoldings,
  createDefaultFundamentalDraft,
  toSlashDate,
  flashSaved,
  setTab,
}) {
  return {
    holdings: holdings || [],
    tradeLog: tradeLog || [],
    marketQuotes: marketQuotes || null,
    setHoldings,
    setTradeLog,
    upsertTargetReport,
    upsertFundamentalsEntry,
    applyTradeEntryToHoldings,
    createDefaultFundamentalDraft,
    toSlashDate,
    flashSaved,
    afterSubmit: ({ remainingUploads }) => {
      if (remainingUploads === 0) setTab('holdings')
    },
  }
}

export function composeResearchWorkflowArgs({
  researching,
  setResearching,
  setResearchTarget,
  holdings,
  dossierByCode,
  stockMeta,
  strategyBrain,
  portfolioNotes,
  canUseCloud,
  newsEvents,
  analysisHistory,
  resolveHoldingPrice,
  getHoldingUnrealizedPnl,
  getHoldingReturnPct,
  setResearchResults,
  setResearchHistory,
  setStrategyBrain,
  flashSaved,
  enrichResearchToDossier,
}) {
  return {
    researching,
    setResearching,
    setResearchTarget,
    holdings,
    portfolioHoldings: holdings,
    dossierByCode,
    stockMeta,
    strategyBrain,
    portfolioNotes,
    canUseCloud,
    newsEvents,
    analysisHistory,
    resolveHoldingPrice,
    getHoldingUnrealizedPnl,
    getHoldingReturnPct,
    setResearchResults,
    setResearchHistory,
    setStrategyBrain,
    notifySaved: flashSaved,
    enrichResearchToDossier,
  }
}

export function composeLocalBackupWorkflowArgs({
  portfolios,
  activePortfolioId,
  viewMode,
  marketQuotes,
  requestAppConfirmation,
  applyPortfolioSnapshot,
  setPortfolios,
  setActivePortfolioId,
  setViewMode,
  setCloudSync,
  flashSaved,
}) {
  return {
    portfolios,
    activePortfolioId,
    viewMode,
    marketQuotes: marketQuotes || null,
    requestConfirmation: requestAppConfirmation,
    applyPortfolioSnapshot,
    setPortfolios,
    setActivePortfolioId,
    setViewMode,
    setCloudSync,
    flashSaved,
  }
}

export function composePortfolioPanelsContextInput({
  data,
  ui,
  asyncState,
  resources,
  controls,
  actions,
}) {
  return {
    activePortfolioId: data.activePortfolioId,
    overviewPortfolios: data.overviewPortfolios,
    overviewTotalValue: data.overviewTotalValue,
    overviewTotalPnl: data.overviewTotalPnl,
    overviewDuplicateHoldings: data.overviewDuplicateHoldings,
    overviewPendingItems: data.overviewPendingItems,
    holdings: data.holdings,
    totalVal: data.totalVal,
    totalCost: data.totalCost,
    todayTotalPnl: data.todayTotalPnl,
    winners: data.winners,
    losers: data.losers,
    top5: data.top5,
    holdingsIntegrityIssues: data.holdingsIntegrityIssues,
    showReversal: ui.showReversal,
    reversalConditions: ui.reversalConditions,
    reviewingEvent: ui.reviewingEvent,
    attentionCount: ui.attentionCount,
    pendingCount: ui.pendingCount,
    targetUpdateCount: ui.targetUpdateCount,
    scanQuery: ui.scanQuery,
    scanFilter: ui.scanFilter,
    sortBy: ui.sortBy,
    expandedStock: ui.expandedStock,
    watchlistFocus: ui.watchlistFocus,
    watchlistRows: ui.watchlistRows,
    showRelayPlan: ui.showRelayPlan,
    relayPlanExpanded: ui.relayPlanExpanded,
    filterType: ui.filterType,
    filteredEvents: data.filteredEvents,
    catalystFilter: ui.catalystFilter,
    morningNote: data.morningNote,
    dailyReport: data.dailyReport,
    analysisHistory: data.analysisHistory,
    analyzing: asyncState.analyzing,
    analyzeStep: asyncState.analyzeStep,
    stressResult: asyncState.stressResult,
    stressTesting: asyncState.stressTesting,
    dailyExpanded: ui.dailyExpanded,
    newsEvents: data.newsEvents,
    strategyBrain: data.strategyBrain,
    researching: asyncState.researching,
    researchTarget: ui.researchTarget,
    reportRefreshing: asyncState.reportRefreshing,
    reportRefreshStatus: asyncState.reportRefreshStatus,
    dataRefreshRows: data.dataRefreshRows,
    researchResults: resources.researchResults,
    researchHistory: data.researchHistory,
    enrichingResearchCode: asyncState.enrichingResearchCode,
    proposalActionId: asyncState.proposalActionId,
    proposalActionType: asyncState.proposalActionType,
    tradeLog: data.tradeLog,
    reviewForm: ui.reviewForm,
    expandedNews: ui.expandedNews,
    stockMeta: resources.stockMeta,
    indColor: resources.indColor,
    tradeCapture: resources.tradeCapture,
    exitOverview: controls.exitOverview,
    switchPortfolio: controls.switchPortfolio,
    setShowReversal: controls.setShowReversal,
    setReviewingEvent: controls.setReviewingEvent,
    updateReversal: controls.updateReversal,
    setScanQuery: controls.setScanQuery,
    setScanFilter: controls.setScanFilter,
    setSortBy: controls.setSortBy,
    setExpandedStock: controls.setExpandedStock,
    updateTargetPrice: actions.updateTargetPrice,
    updateAlert: actions.updateAlert,
    handleWatchlistUpsert: actions.handleWatchlistUpsert,
    handleWatchlistDelete: actions.handleWatchlistDelete,
    formatEventStockOutcomeLine: actions.formatEventStockOutcomeLine,
    setRelayPlanExpanded: controls.setRelayPlanExpanded,
    setFilterType: controls.setFilterType,
    setCatalystFilter: controls.setCatalystFilter,
    setDailyExpanded: controls.setDailyExpanded,
    runDailyAnalysis: actions.runDailyAnalysis,
    maybeAutoConfirmDailyReport: actions.maybeAutoConfirmDailyReport,
    runStressTest: actions.runStressTest,
    setStressResult: controls.setStressResult,
    setTab: controls.setTab,
    setExpandedNews: controls.setExpandedNews,
    refreshAnalystReports: actions.refreshAnalystReports,
    runResearch: actions.runResearch,
    enrichResearchToDossier: actions.enrichResearchToDossier,
    applyBrainProposal: actions.applyBrainProposal,
    discardBrainProposal: actions.discardBrainProposal,
    setResearchResults: controls.setResearchResults,
    setReviewForm: controls.setReviewForm,
    submitReview: actions.submitReview,
    cancelReview: actions.cancelReview,
    createDefaultReviewForm: resources.createDefaultReviewForm,
  }
}
