export function composeAppHeaderProps({
  theme,
  sync,
  pnl,
  portfolio,
  overview,
  notes,
  tabs,
  dialogs,
  constants,
}) {
  return {
    C: theme.C,
    pc: theme.pc,
    cloudSync: sync.cloudSync,
    saved: sync.saved,
    refreshPrices: sync.refreshPrices,
    refreshing: sync.refreshing,
    copyWeeklyReport: sync.copyWeeklyReport,
    downloadWeeklyReportMarkdown: sync.downloadWeeklyReportMarkdown,
    downloadWeeklyReportHtml: sync.downloadWeeklyReportHtml,
    downloadWeeklyReportPdf: sync.downloadWeeklyReportPdf,
    exportLocalBackup: sync.exportLocalBackup,
    backupFileInputRef: sync.backupFileInputRef,
    importLocalBackup: sync.importLocalBackup,
    priceSyncStatusTone: sync.priceSyncStatusTone,
    priceSyncStatusLabel: sync.priceSyncStatusLabel,
    activePriceSyncAt: sync.activePriceSyncAt,
    lastUpdate: sync.lastUpdate,
    displayedTotalPnl: pnl.displayedTotalPnl,
    displayedRetPct: pnl.displayedRetPct,
    activePortfolioId: portfolio.activePortfolioId,
    switchPortfolio: portfolio.switchPortfolio,
    ready: portfolio.ready,
    portfolioSwitching: portfolio.portfolioSwitching,
    portfolioSummaries: portfolio.portfolioSummaries,
    createPortfolio: portfolio.createPortfolio,
    viewMode: portfolio.viewMode,
    exitOverview: portfolio.exitOverview,
    openOverview: portfolio.openOverview,
    showPortfolioManager: portfolio.showPortfolioManager,
    setShowPortfolioManager: portfolio.setShowPortfolioManager,
    renamePortfolio: portfolio.renamePortfolio,
    deletePortfolio: portfolio.deletePortfolio,
    OWNER_PORTFOLIO_ID: constants.OWNER_PORTFOLIO_ID,
    overviewTotalValue: overview.overviewTotalValue,
    portfolioNotes: notes.portfolioNotes,
    setPortfolioNotes: notes.setPortfolioNotes,
    PORTFOLIO_VIEW_MODE: constants.PORTFOLIO_VIEW_MODE,
    OVERVIEW_VIEW_MODE: constants.OVERVIEW_VIEW_MODE,
    urgentCount: tabs.urgentCount,
    todayAlertSummary: tabs.todayAlertSummary,
    TABS: tabs.portfolioTabs,
    tab: tabs.tab,
    setTab: tabs.setTab,
    workflowCue: tabs.workflowCue ?? null,
    portfolioEditor: dialogs.portfolioEditor,
    portfolioDeleteDialog: dialogs.portfolioDeleteDialog,
  }
}
