import { useMemo } from 'react'

export function usePortfolioPanelsContextComposer({
  activePortfolioId,
  overviewPortfolios,
  overviewTotalValue,
  overviewTotalPnl,
  overviewDuplicateHoldings,
  overviewPendingItems,
  holdings,
  totalVal,
  totalCost,
  winners,
  losers,
  top5,
  holdingsIntegrityIssues,
  showReversal,
  reversalConditions,
  reviewingEvent,
  attentionCount,
  pendingCount,
  targetUpdateCount,
  scanQuery,
  scanFilter,
  sortBy,
  expandedStock,
  watchlistFocus,
  watchlistRows,
  showRelayPlan,
  relayPlanExpanded,
  filterType,
  filteredEvents,
  catalystFilter,
  morningNote,
  dailyReport,
  analyzing,
  analyzeStep,
  stressResult,
  stressTesting,
  dailyExpanded,
  newsEvents,
  strategyBrain,
  researching,
  researchTarget,
  reportRefreshing,
  reportRefreshStatus,
  dataRefreshRows,
  researchResults,
  researchHistory,
  enrichingResearchCode,
  proposalActionId,
  proposalActionType,
  tradeLog,
  reviewForm,
  expandedNews,
  stockMeta,
  indColor,
  tradeCapture,
  exitOverview,
  switchPortfolio,
  setShowReversal,
  setReviewingEvent,
  updateReversal,
  setScanQuery,
  setScanFilter,
  setSortBy,
  setExpandedStock,
  updateTargetPrice,
  updateAlert,
  handleWatchlistUpsert,
  handleWatchlistDelete,
  formatEventStockOutcomeLine,
  setRelayPlanExpanded,
  setFilterType,
  setCatalystFilter,
  setDailyExpanded,
  runDailyAnalysis,
  runStressTest,
  setStressResult,
  setTab,
  setExpandedNews,
  refreshAnalystReports,
  runResearch,
  applyBrainProposal,
  discardBrainProposal,
  enrichResearchToDossier,
  setResearchResults,
  setReviewForm,
  submitReview,
  cancelReview,
  createDefaultReviewForm,
}) {
  const portfolioPanelsData = useMemo(
    () => ({
      overview: {
        portfolioCount: overviewPortfolios.length,
        totalValue: overviewTotalValue,
        totalPnl: overviewTotalPnl,
        portfolios: overviewPortfolios,
        activePortfolioId,
        duplicateHoldings: overviewDuplicateHoldings,
        pendingItems: overviewPendingItems,
      },
      holdings: {
        holdings,
        totalVal,
        totalCost,
        winners,
        losers,
        top5,
        holdingsIntegrityIssues,
        showReversal,
        reversalConditions,
        reviewingEvent,
        attentionCount,
        pendingCount,
        targetUpdateCount,
        scanQuery,
        scanFilter,
        sortBy,
        expandedStock,
      },
      holdingsTable: {
        holdings,
        expandedStock,
      },
      watchlist: {
        watchlistFocus,
        watchlistRows,
        expandedStock,
      },
      events: {
        showRelayPlan,
        relayPlanExpanded,
        filterType,
        filteredEvents,
        catalystFilter,
      },
      daily: {
        morningNote,
        dailyReport,
        analyzing,
        analyzeStep,
        stressResult,
        stressTesting,
        dailyExpanded,
        newsEvents,
        expandedStock,
        strategyBrain,
      },
      research: {
        holdings,
        researching,
        researchTarget,
        reportRefreshing,
        reportRefreshStatus,
        dataRefreshRows,
        researchResults,
        researchHistory,
        enrichingResearchCode,
        proposalActionId,
        proposalActionType,
        STOCK_META: stockMeta,
        IND_COLOR: indColor,
      },
      trade: {
        ...tradeCapture,
      },
      log: {
        tradeLog,
      },
      news: {
        newsEvents,
        reviewingEvent,
        reviewForm,
        expandedNews,
      },
    }),
    [
      activePortfolioId,
      analyzing,
      analyzeStep,
      attentionCount,
      catalystFilter,
      dailyExpanded,
      dailyReport,
      dataRefreshRows,
      enrichingResearchCode,
      expandedNews,
      expandedStock,
      filterType,
      filteredEvents,
      holdings,
      holdingsIntegrityIssues,
      indColor,
      losers,
      morningNote,
      newsEvents,
      overviewDuplicateHoldings,
      overviewPendingItems,
      overviewPortfolios,
      overviewTotalPnl,
      overviewTotalValue,
      pendingCount,
      relayPlanExpanded,
      reportRefreshing,
      reportRefreshStatus,
      researchHistory,
      researchResults,
      researchTarget,
      researching,
      proposalActionId,
      proposalActionType,
      reviewForm,
      reviewingEvent,
      reversalConditions,
      scanFilter,
      scanQuery,
      showRelayPlan,
      showReversal,
      sortBy,
      stockMeta,
      strategyBrain,
      stressResult,
      stressTesting,
      targetUpdateCount,
      top5,
      totalCost,
      totalVal,
      tradeCapture,
      tradeLog,
      watchlistFocus,
      watchlistRows,
      winners,
    ]
  )

  const portfolioPanelsActions = useMemo(
    () => ({
      overview: {
        onExit: exitOverview,
        onSwitch: switchPortfolio,
      },
      holdings: {
        setShowReversal,
        setReviewingEvent,
        updateReversal,
        setScanQuery,
        setScanFilter,
        setSortBy,
        setExpandedStock,
      },
      holdingsTable: {
        setExpandedStock,
        onUpdateTarget: updateTargetPrice,
        onUpdateAlert: updateAlert,
      },
      watchlist: {
        setExpandedStock,
        onUpsertItem: handleWatchlistUpsert,
        handleWatchlistDelete,
        formatEventStockOutcomeLine,
      },
      events: {
        setRelayPlanExpanded,
        setFilterType,
        setCatalystFilter,
      },
      daily: {
        setDailyExpanded,
        runDailyAnalysis,
        runStressTest,
        closeStressResult: () => setStressResult(null),
        setTab,
        setExpandedNews,
        setExpandedStock,
      },
      research: {
        onEvolve: () => runResearch('evolve'),
        onRefresh: () => refreshAnalystReports({ force: true }),
        onResearch: runResearch,
        onEnrich: enrichResearchToDossier,
        onApplyProposal: applyBrainProposal,
        onDiscardProposal: discardBrainProposal,
        onSelectHistory: setResearchResults,
      },
      trade: {
        setDragOver: tradeCapture.setDragOver,
        processFile: tradeCapture.processFile,
        processFiles: tradeCapture.processFiles,
        parseShot: tradeCapture.parseShot,
        setParsed: tradeCapture.setParsed,
        setTradeDate: tradeCapture.setTradeDate,
        setMemoIn: tradeCapture.setMemoIn,
        submitMemo: tradeCapture.submitMemo,
        selectUpload: tradeCapture.selectUpload,
        removeUpload: tradeCapture.removeUpload,
        clearUploads: tradeCapture.clearUploads,
        setTpCode: tradeCapture.setTpCode,
        setTpFirm: tradeCapture.setTpFirm,
        setTpVal: tradeCapture.setTpVal,
        setFundamentalDraft: tradeCapture.setFundamentalDraft,
        upsertTargetReport: tradeCapture.upsertTargetReport,
        upsertFundamentalsEntry: tradeCapture.upsertFundamentalsEntry,
        createDefaultFundamentalDraft: tradeCapture.createDefaultFundamentalDraft,
        toSlashDate: tradeCapture.toSlashDate,
      },
      news: {
        setReviewForm,
        submitReview,
        cancelReview,
        setExpandedNews,
        setTab,
        setReviewingEvent,
        createDefaultReviewForm,
      },
    }),
    [
      cancelReview,
      createDefaultReviewForm,
      enrichResearchToDossier,
      exitOverview,
      formatEventStockOutcomeLine,
      handleWatchlistDelete,
      handleWatchlistUpsert,
      applyBrainProposal,
      discardBrainProposal,
      refreshAnalystReports,
      runDailyAnalysis,
      runResearch,
      runStressTest,
      setCatalystFilter,
      setDailyExpanded,
      setExpandedNews,
      setExpandedStock,
      setFilterType,
      setRelayPlanExpanded,
      setResearchResults,
      setReviewForm,
      setReviewingEvent,
      setScanFilter,
      setScanQuery,
      setShowReversal,
      setSortBy,
      setStressResult,
      setTab,
      submitReview,
      switchPortfolio,
      tradeCapture,
      updateAlert,
      updateReversal,
      updateTargetPrice,
    ]
  )

  return { portfolioPanelsData, portfolioPanelsActions }
}
