import { describe, expect, it, vi } from 'vitest'
import {
  useAppRuntimeCoreArgs,
  useAppRuntimeWorkflowArgs,
} from '../../src/hooks/useAppRuntimeArgs.js'

describe('hooks/useAppRuntimeArgs', () => {
  it('builds core lifecycle args from grouped runtime buckets', () => {
    const coreArgs = useAppRuntimeCoreArgs({
      state: {
        ready: true,
        holdings: [],
        watchlist: [],
        newsEvents: [],
        tradeLog: [],
        targets: {},
        fundamentals: {},
        analystReports: {},
        reportRefreshMeta: {},
        holdingDossiers: {},
        analysisHistory: [],
        dailyReport: null,
        reversalConditions: {},
        strategyBrain: {},
        brainValidation: {},
        researchHistory: [],
        portfolioNotes: {},
      },
      setters: {
        setReady: vi.fn(),
        setCloudSync: vi.fn(),
        setHoldings: vi.fn(),
        setTradeLog: vi.fn(),
        setTargets: vi.fn(),
        setFundamentals: vi.fn(),
        setWatchlist: vi.fn(),
        setAnalystReports: vi.fn(),
        setReportRefreshMeta: vi.fn(),
        setHoldingDossiers: vi.fn(),
        setNewsEvents: vi.fn(),
        setAnalysisHistory: vi.fn(),
        setReversalConditions: vi.fn(),
        setStrategyBrain: vi.fn(),
        setBrainValidation: vi.fn(),
        setResearchHistory: vi.fn(),
        setPortfolioNotes: vi.fn(),
        setDailyReport: vi.fn(),
      },
      ui: {
        tab: 'holdings',
        resetTransientUiState: vi.fn(),
        setReviewingEvent: vi.fn(),
        setReviewForm: vi.fn(),
      },
      runtime: {
        flashSaved: vi.fn(),
        requestAppConfirmation: vi.fn(),
      },
      refs: {
        activePortfolioIdRef: { current: 'me' },
        viewModeRef: { current: 'portfolio' },
        portfoliosRef: { current: [] },
        portfolioSetterRef: { current: { setActivePortfolioId: vi.fn(), setViewMode: vi.fn() } },
        bootRuntimeRef: { current: null },
        cloudSyncStateRef: { current: { enabled: false } },
        cloudSaveTimersRef: { current: {} },
      },
      helpers: { normalizeHoldings: vi.fn() },
    })

    expect(coreArgs.state.ready).toBe(true)
    expect(coreArgs.state.tab).toBe('holdings')
    expect(coreArgs.refs.activePortfolioIdRef.current).toBe('me')
    expect(typeof coreArgs.helpers.normalizeHoldings).toBe('function')
  })

  it('builds workflow args from grouped state/derived/ui buckets', () => {
    const workflowArgs = useAppRuntimeWorkflowArgs({
      state: {
        ready: true,
        viewMode: 'portfolio',
        portfolioViewMode: 'portfolio',
        activePortfolioId: 'me',
        canUseCloud: true,
        holdings: [],
        tradeLog: [],
        marketPriceCache: { prices: {} },
        newsEvents: [],
        analysisHistory: [],
        strategyBrain: {},
        portfolioNotes: {},
        reversalConditions: {},
        reportRefreshMeta: {},
        researchHistory: [],
        analystReports: {},
        portfolios: [],
        morningNote: { text: 'ok' },
        dailyReport: null,
      },
      derived: {
        todayMarketClock: { date: '2026-03-31' },
        shouldTriggerPostCloseSelfHeal: false,
        todayRefreshKey: '2026-03-31',
        dossierByCode: {},
        H: [],
        W: [],
        totalCost: 0,
        totalVal: 0,
        totalPnl: 0,
        retPct: 0,
        overviewPortfolios: [],
        overviewTotalValue: 0,
        overviewTotalPnl: 0,
        overviewDuplicateHoldings: [],
        overviewPendingItems: [],
        winners: [],
        losers: [],
        top5: [],
        holdingsIntegrityIssues: [],
        attentionCount: 0,
        pendingCount: 0,
        targetUpdateCount: 0,
        dataRefreshRows: [],
        reportRefreshCandidates: [],
        watchlistRows: [],
        watchlistFocus: null,
        showRelayPlan: false,
      },
      ui: {
        tab: 'news',
        detailStockCode: '2330',
        filterType: 'all',
        catalystFilter: '全部',
        scanQuery: '',
        scanFilter: '',
        sortBy: 'pnl',
        showReversal: false,
        expandedStock: null,
        relayPlanExpanded: false,
        dailyExpanded: false,
        researchTarget: '',
        reviewForm: {},
        reviewingEvent: null,
        expandedNews: null,
      },
      asyncState: {
        analyzing: false,
        setAnalyzing: vi.fn(),
        analyzeStep: '',
        setAnalyzeStep: vi.fn(),
        researching: false,
        setResearching: vi.fn(),
      },
      actions: {
        upsertTargetReport: vi.fn(),
        upsertFundamentalsEntry: vi.fn(),
        updateReversal: vi.fn(),
        updateTargetPrice: vi.fn(),
        updateAlert: vi.fn(),
        handleWatchlistUpsert: vi.fn(),
        handleWatchlistDelete: vi.fn(),
        cancelReview: vi.fn(),
        switchPortfolio: vi.fn(),
        exitOverview: vi.fn(),
      },
      setters: {
        setResearchTarget: vi.fn(),
        setResearchResults: vi.fn(),
        setReviewForm: vi.fn(),
        setReviewingEvent: vi.fn(),
        setAnalystReports: vi.fn(),
        setReportRefreshMeta: vi.fn(),
        setNewsEvents: vi.fn(),
        setStrategyBrain: vi.fn(),
        setBrainValidation: vi.fn(),
        setDailyReport: vi.fn(),
        setAnalysisHistory: vi.fn(),
        setHoldings: vi.fn(),
        setLastUpdate: vi.fn(),
        setTradeLog: vi.fn(),
        setResearchHistory: vi.fn(),
        setPortfolios: vi.fn(),
        setActivePortfolioId: vi.fn(),
        setViewMode: vi.fn(),
        setCloudSync: vi.fn(),
        setShowReversal: vi.fn(),
        setScanQuery: vi.fn(),
        setScanFilter: vi.fn(),
        setSortBy: vi.fn(),
        setExpandedStock: vi.fn(),
        setDetailStockCode: vi.fn(),
        setRelayPlanExpanded: vi.fn(),
        setFilterType: vi.fn(),
        setCatalystFilter: vi.fn(),
        setDailyExpanded: vi.fn(),
        setTab: vi.fn(),
        setExpandedNews: vi.fn(),
      },
      resources: {
        defaultNewsEvents: [],
        researchResults: null,
        stockMeta: {},
        indColor: {},
      },
      runtime: {
        flashSaved: vi.fn(),
        requestAppConfirmation: vi.fn(),
      },
      refs: {
        priceSelfHealRef: { current: null },
        syncPostClosePrices: vi.fn(),
        refreshAnalystReportsRef: { current: vi.fn() },
        resetTradeCaptureRef: { current: vi.fn() },
        applyPortfolioSnapshot: vi.fn(),
        portfolioTransitionRef: { current: { isHydrating: false } },
        cloudSyncStateRef: { current: { enabled: false } },
        livePortfolioSnapshot: vi.fn(),
      },
      helpers: { resolveHoldingPrice: vi.fn() },
    })

    expect(workflowArgs.state.viewMode).toBe('portfolio')
    expect(workflowArgs.state.canUseCloud).toBe(true)
    expect(workflowArgs.derived.watchlistRows).toEqual([])
    expect(workflowArgs.ui.tab).toBe('news')
    expect(workflowArgs.ui.detailStockCode).toBe('2330')
    expect(workflowArgs.refs.priceSelfHealRef.current).toBeNull()
    expect(typeof workflowArgs.helpers.resolveHoldingPrice).toBe('function')
  })
})
