import { C } from './theme.js'

// Re-export from split modules (not needed at boot time, but kept for backward compat)
export { NEWS_EVENTS, RELAY_PLAN, RELAY_PLAN_CODES } from './seedDataEvents.js'
export { INIT_HOLDINGS_JINLIANCHENG, INIT_TARGETS_JINLIANCHENG } from './seedDataJinliancheng.js'

// ── 目標價資料庫（分析師共識）─────────────────────────────────────
// reports: [{firm, target, date}]  avg 自動計算
export const INIT_TARGETS = {
  1503: {
    reports: [{ firm: '自行估算', target: 260, date: '2026/03' }],
    updatedAt: '2026/03/17',
    isNew: false,
  },
  1717: {
    reports: [{ firm: '自行估算', target: 75, date: '2026/03' }],
    updatedAt: '2026/03/17',
    isNew: false,
  },
  2308: {
    reports: [
      { firm: '元大', target: 1200, date: '2026/01' },
      { firm: '富邦', target: 1150, date: '2026/02' },
      { firm: 'FactSet共識', target: 1575, date: '2026/02/27' },
    ],
    updatedAt: '2026/04/01',
    isNew: false,
  },
  2313: {
    reports: [
      { firm: '凱基', target: 280, date: '2026/01' },
      { firm: 'FactSet共識', target: 280, date: '2026/01' },
      { firm: 'FactSet共識', target: 210, date: '2026/03/16' },
    ],
    updatedAt: '2026/04/01',
    isNew: false,
  },
  2543: {
    reports: [{ firm: '自行估算', target: 90, date: '2026/03' }],
    updatedAt: '2026/03/17',
    isNew: false,
  },
  3006: {
    reports: [
      { firm: '華南投顧', target: 200, date: '2026/03/11' },
      { firm: '法人A', target: 205, date: '2026/03/16' },
      { firm: '法人B', target: 246, date: '2026/03/16' },
    ],
    updatedAt: '2026/03/16',
    isNew: true,
  },
  3013: {
    reports: [{ firm: '自行估算', target: 120, date: '2026/03' }],
    updatedAt: '2026/03/17',
    isNew: false,
  },
  3017: {
    reports: [
      { firm: '國際共識', target: 2037, date: '2026/03' },
      { firm: '大摩', target: 1800, date: '2025/11' },
      { firm: '大和', target: 1840, date: '2025/10' },
      { firm: '大摩', target: 2300, date: '2026/03/13' },
    ],
    updatedAt: '2026/04/01',
    isNew: true,
  },
  3231: {
    reports: [
      { firm: '中信投顧', target: 195, date: '2026/03/16' },
      { firm: '國內法人', target: 188, date: '2026/03/16' },
    ],
    updatedAt: '2026/04/01',
    isNew: true,
  },
  3443: {
    reports: [
      { firm: '中信投顧', target: 3600, date: '2026/02' },
      { firm: '元大投顧', target: 3400, date: '2026/02' },
      { firm: '大摩', target: 3288, date: '2026/02' },
    ],
    updatedAt: '2026/02/04',
    isNew: true,
  },
  3491: {
    reports: [{ firm: '自行估算', target: 1600, date: '2026/03' }],
    updatedAt: '2026/03/17',
    isNew: false,
  },
  4583: {
    reports: [{ firm: '自行估算', target: 750, date: '2026/03' }],
    updatedAt: '2026/03/17',
    isNew: false,
  },
  6274: {
    reports: [{ firm: '中信投顧', target: 710, date: '2026/03/12' }],
    updatedAt: '2026/03/12',
    isNew: true,
  },
  6770: {
    reports: [{ firm: '自行估算', target: 100, date: '2026/03' }],
    updatedAt: '2026/03/17',
    isNew: false,
  },
  6862: {
    reports: [{ firm: '自行估算', target: 230, date: '2026/03' }],
    updatedAt: '2026/03/17',
    isNew: false,
  },
  8227: {
    reports: [{ firm: '中信投顧', target: 190, date: '2026/01/23' }],
    updatedAt: '2026/01/23',
    isNew: false,
  },
}

export const avgTarget = (code) => {
  const d = INIT_TARGETS[code]
  if (!d || !d.reports.length) return null
  return Math.round(d.reports.reduce((s, r) => s + r.target, 0) / d.reports.length)
}

// ── 產業/策略 metadata ──────────────────────────────────────────
export const STOCK_META = {
  // ── me 組合 ──
  '00637L': {
    industry: '中國ETF',
    strategy: 'ETF/指數',
    period: '短中',
    position: '戰術',
    leader: 'N/A',
  },
  '039108': {
    industry: '被動元件',
    strategy: '權證',
    period: '短',
    position: '戰術',
    leader: 'N/A',
    underlying: '禾伸堂',
    underlyingCode: '3115',
  },
  '053848': {
    industry: '半導體設備',
    strategy: '權證',
    period: '短',
    position: '戰術',
    leader: 'N/A',
    underlying: '亞翔',
    underlyingCode: '6139',
  },
  702157: {
    industry: '光通訊',
    strategy: '權證',
    period: '短',
    position: '戰術',
    leader: 'N/A',
    underlying: '華星光',
    underlyingCode: '4979',
  },
  705200: {
    industry: '製鞋/紡織',
    strategy: '權證',
    period: '短',
    position: '戰術',
    leader: 'N/A',
    underlying: '加百裕',
    underlyingCode: '3323',
  },
  1503: {
    industry: '重電',
    strategy: '景氣循環',
    period: '中',
    position: '衛星',
    leader: '二線',
    themes: ['電動車'],
  },
  1717: {
    industry: 'PCB/材料',
    strategy: '景氣循環',
    period: '中',
    position: '衛星',
    leader: '龍頭',
    themes: ['CoWoS', 'Apple'],
  },
  2308: {
    industry: 'AI/伺服器',
    strategy: '成長股',
    period: '中長',
    position: '核心',
    leader: '龍頭',
    themes: ['AI伺服器', 'NVIDIA', '資料中心', '電動車', '碳化矽'],
  },
  2313: {
    industry: 'PCB/材料',
    strategy: '景氣循環',
    period: '中',
    position: '衛星',
    leader: '二線',
    themes: ['低軌衛星'],
  },
  2543: { industry: '營建', strategy: '景氣循環', period: '中', position: '戰術', leader: '小型' },
  3006: {
    industry: 'IC/記憶體',
    strategy: '景氣循環',
    period: '短中',
    position: '戰術',
    leader: '小型',
  },
  3013: {
    industry: 'AI/伺服器',
    strategy: '成長股',
    period: '中',
    position: '衛星',
    leader: '小型',
    themes: ['AI伺服器', 'NVIDIA'],
  },
  3017: {
    industry: 'AI/伺服器',
    strategy: '成長股',
    period: '中長',
    position: '核心',
    leader: '龍頭',
    themes: ['AI伺服器', 'NVIDIA', '資料中心'],
  },
  3231: {
    industry: 'AI/伺服器',
    strategy: '成長股',
    period: '中',
    position: '衛星',
    leader: '大型',
    themes: ['AI伺服器', 'NVIDIA', 'HBM', 'ABF載板', '資料中心'],
  },
  3443: {
    industry: 'AI/伺服器',
    strategy: '成長股',
    period: '中長',
    position: '核心',
    leader: '龍頭',
    themes: ['AI伺服器', 'NVIDIA', 'CoWoS'],
  },
  3491: {
    industry: '光通訊',
    strategy: '成長股',
    period: '中長',
    position: '核心',
    leader: '小龍頭',
    themes: ['CPO', '5G', '低軌衛星', '資料中心'],
  },
  4583: {
    industry: '精密機械',
    strategy: '事件驅動',
    period: '中',
    position: '衛星',
    leader: '小型',
  },
  6274: {
    industry: 'PCB/材料',
    strategy: '景氣循環',
    period: '中',
    position: '衛星',
    leader: '二線',
    themes: ['NVIDIA', '低軌衛星'],
  },
  6770: {
    industry: 'IC/記憶體',
    strategy: '景氣循環',
    period: '中長',
    position: '衛星',
    leader: '二線',
    themes: ['HBM', '矽晶圓'],
  },
  6862: {
    industry: '被動元件/電感',
    strategy: '成長股',
    period: '中',
    position: '衛星',
    leader: '小龍頭',
    themes: ['AI伺服器', 'NVIDIA', '被動元件'],
  },
  8227: {
    industry: '光通訊',
    strategy: '成長股',
    period: '中長',
    position: '衛星',
    leader: '小型',
    themes: ['CoWoS'],
  },
  // ── 金聯成 組合 ──
  '0050': {
    industry: '台股ETF',
    strategy: 'ETF/指數',
    period: '中長',
    position: '衛星',
    leader: 'N/A',
  },
  '00635U': {
    industry: '商品ETF',
    strategy: 'ETF/指數',
    period: '中',
    position: '戰術',
    leader: 'N/A',
  },
  '00918': {
    industry: '高股息ETF',
    strategy: 'ETF/指數',
    period: '中長',
    position: '衛星',
    leader: 'N/A',
  },
  '00981A': {
    industry: '主動型ETF',
    strategy: 'ETF/指數',
    period: '中長',
    position: '衛星',
    leader: 'N/A',
  },
  1799: {
    industry: '生技醫療',
    strategy: '轉型股',
    period: '中',
    position: '核心',
    leader: '小型',
  },
  1815: {
    industry: 'PCB/材料',
    strategy: '景氣循環',
    period: '中',
    position: '衛星',
    leader: '二線',
  },
  2489: {
    industry: '顯示器/光電',
    strategy: '轉型股',
    period: '中',
    position: '核心',
    leader: '中型',
  },
  3167: {
    industry: '精密機械',
    strategy: '成長股',
    period: '中',
    position: '衛星',
    leader: '小龍頭',
  },
  4562: {
    industry: '精密機械',
    strategy: '景氣循環',
    period: '中',
    position: '衛星',
    leader: '小型',
  },
  6446: {
    industry: '生技醫療',
    strategy: '成長股',
    period: '中長',
    position: '核心',
    leader: '龍頭',
  },
  7799: {
    industry: '生技醫療',
    strategy: '成長股',
    period: '中長',
    position: '核心',
    leader: '小龍頭',
  },
  7865: {
    industry: '環保/循環',
    strategy: '價值股',
    period: '中長',
    position: '核心',
    leader: '小龍頭',
  },
  8074: {
    industry: 'PCB/材料',
    strategy: '景氣循環',
    period: '中',
    position: '衛星',
    leader: '小型',
  },
  8096: {
    industry: '電子通路',
    strategy: '成長股',
    period: '中',
    position: '衛星',
    leader: '中型',
  },
}

// 產業色彩映射 — 提亮版（文字用，需在 #283D3B 上可讀）
export const IND_COLOR = {
  'AI/伺服器': C.teal,
  光通訊: C.cyan,
  'PCB/材料': C.amber,
  'IC/記憶體': C.lavender,
  被動元件: C.orange,
  '被動元件/電感': C.orange,
  重電: C.up,
  營建: C.olive,
  精密機械: C.stone,
  連接器: C.mint,
  中國ETF: C.rose,
  半導體設備: C.choco,
  // 金聯成 組合新增產業
  生技醫療: C.up,
  台股ETF: C.blue,
  高股息ETF: C.blue,
  主動型ETF: C.blue,
  商品ETF: C.amber,
  '顯示器/光電': C.rose,
  '環保/循環': C.olive,
  電子通路: C.lavender,
}

// ── 初始持倉 ────────────────────────────────────────────────────
export const INIT_HOLDINGS = [
  {
    code: '00637L',
    name: '滬深300正2',
    qty: 141,
    price: 19.96,
    cost: 18.99,
    value: 2814,
    pnl: 134,
    pct: 5.01,
    type: 'ETF',
  },
  {
    code: '053848',
    name: '亞翔凱基5B購',
    qty: 8000,
    price: 2.23,
    cost: 1.81,
    value: 17840,
    pnl: 3234,
    pct: 22.32,
    type: '權證',
  },
  {
    code: '702157',
    name: '華星光元大58購',
    qty: 4000,
    price: 3.35,
    cost: 1.29,
    value: 13400,
    pnl: 8167,
    pct: 157.66,
    type: '權證',
  },
  {
    code: '705200',
    name: '加百裕國票58購01',
    qty: 8000,
    price: 1.06,
    cost: 1.06,
    value: 8480,
    pnl: 0,
    pct: 0,
    type: '權證',
  },
  {
    code: '1503',
    name: '士電',
    qty: 9,
    price: 205,
    cost: 229.5,
    value: 1845,
    pnl: -227,
    pct: -10.99,
    type: '股票',
  },
  {
    code: '1717',
    name: '長興',
    qty: 43,
    price: 63.7,
    cost: 66.1,
    value: 2737,
    pnl: -118,
    pct: -4.15,
    type: '股票',
  },
  {
    code: '2308',
    name: '台達電',
    qty: 2,
    price: 1440,
    cost: 1287.5,
    value: 2880,
    pnl: 293,
    pct: 11.37,
    type: '股票',
  },
  {
    code: '2313',
    name: '華通',
    qty: 40,
    price: 236.5,
    cost: 187.5,
    value: 9457,
    pnl: 1920,
    pct: 25.58,
    type: '股票',
  },
  {
    code: '2543',
    name: '皇昌',
    qty: 6,
    price: 71.6,
    cost: 78.3,
    value: 429,
    pnl: -43,
    pct: -9.15,
    type: '股票',
  },
  {
    code: '3006',
    name: '晶豪科',
    qty: 12,
    price: 194.5,
    cost: 164,
    value: 2334,
    pnl: 357,
    pct: 18.13,
    type: '股票',
  },
  {
    code: '3013',
    name: '晟銘電',
    qty: 29,
    price: 99,
    cost: 125.91,
    value: 2871,
    pnl: -791,
    pct: -21.65,
    type: '股票',
  },
  {
    code: '3017',
    name: '奇鋐',
    qty: 2,
    price: 1905,
    cost: 1400,
    value: 3810,
    pnl: 997,
    pct: 35.59,
    type: '股票',
  },
  {
    code: '3231',
    name: '緯創',
    qty: 11,
    price: 134,
    cost: 134.55,
    value: 1474,
    pnl: -14,
    pct: -0.94,
    type: '股票',
  },
  {
    code: '3443',
    name: '創意',
    qty: 3,
    price: 2290,
    cost: 2566.67,
    value: 6870,
    pnl: -854,
    pct: -11.09,
    type: '股票',
  },
  {
    code: '3491',
    name: '昇達科',
    qty: 3,
    price: 1445,
    cost: 1276.67,
    value: 4335,
    pnl: 487,
    pct: 12.71,
    type: '股票',
  },
  {
    code: '4583',
    name: '台灣精銳',
    qty: 5,
    price: 629,
    cost: 734,
    value: 3145,
    pnl: -536,
    pct: -14.6,
    type: '股票',
  },
  {
    code: '6274',
    name: '台燿',
    qty: 3,
    price: 505,
    cost: 507,
    value: 1515,
    pnl: -12,
    pct: -0.79,
    type: '股票',
  },
  {
    code: '6770',
    name: '力積電',
    qty: 20,
    price: 71.7,
    cost: 68.05,
    value: 1433,
    pnl: 63,
    pct: 4.62,
    type: '股票',
  },
  {
    code: '6862',
    name: '三集瑞-KY',
    qty: 17,
    price: 209.5,
    cost: 197.82,
    value: 3560,
    pnl: 182,
    pct: 5.41,
    type: '股票',
  },
  {
    code: '8227',
    name: '巨有科技',
    qty: 21,
    price: 128,
    cost: 146.57,
    value: 2688,
    pnl: -403,
    pct: -13.08,
    type: '股票',
  },
]

export const INIT_WATCHLIST = [
  {
    code: '1513',
    name: '中興電',
    price: 158.5,
    target: 193,
    status: '等Q4財報',
    catalyst: '3–4月財報',
    scKey: 'amber',
    note: '積極163–165元；保守155–160元；催化：台電GIS+台積電',
  },
  {
    code: '4588',
    name: '玖鼎電力',
    price: 69.1,
    target: 154,
    status: '持有中',
    catalyst: '台電電表訂單',
    scKey: 'olive',
    note: '訂單排到2028；現價已偏高不追；持有者繼續抱',
  },
  {
    code: '6274',
    name: '台燿',
    price: 505,
    target: 710,
    status: '⚡法說追蹤',
    catalyst: '3/18法說+財報',
    scKey: 'up',
    note: '成本507；毛利率回沖→補足2/3；展望差→停損430',
  },
]
