import { C } from './theme.js'

// ── 目標價資料庫（分析師共識）─────────────────────────────────────
// reports: [{firm, target, date}]  avg 自動計算
export const INIT_TARGETS = {
  1503: {
    reports: [{ firm: '自行估算', target: 260, date: '2026/03' }],
    updatedAt: '2026/03/17',
    isNew: false,
  },
  1717: {
    reports: [{ firm: '自行估算', target: 75, date: '2026/03' }],
    updatedAt: '2026/03/17',
    isNew: false,
  },
  2308: {
    reports: [{ firm: '元大', target: 1200, date: '2026/01' },
      { firm: '富邦', target: 1150, date: '2026/02' },
      { firm: 'FactSet共識', target: 1575, date: '2026/02/27' }],
    updatedAt: '2026/04/01',
    isNew: false,
  },
  2313: {
    reports: [{ firm: '凱基', target: 280, date: '2026/01' },
      { firm: 'FactSet共識', target: 280, date: '2026/01' },
      { firm: 'FactSet共識', target: 210, date: '2026/03/16' }],
    updatedAt: '2026/04/01',
    isNew: false,
  },
  2543: {
    reports: [{ firm: '自行估算', target: 90, date: '2026/03' }],
    updatedAt: '2026/03/17',
    isNew: false,
  },
  3006: {
    reports: [
      { firm: '華南投顧', target: 200, date: '2026/03/11' },
      { firm: '法人A', target: 205, date: '2026/03/16' },
      { firm: '法人B', target: 246, date: '2026/03/16' },
    ],
    updatedAt: '2026/03/16',
    isNew: true,
  },
  3013: {
    reports: [{ firm: '自行估算', target: 120, date: '2026/03' }],
    updatedAt: '2026/03/17',
    isNew: false,
  },
  3017: {
    reports: [{ firm: '國際共識', target: 2037, date: '2026/03' },
      { firm: '大摩', target: 1800, date: '2025/11' },
      { firm: '大和', target: 1840, date: '2025/10' },
      { firm: '大摩', target: 2300, date: '2026/03/13' }],
    updatedAt: '2026/04/01',
    isNew: true,
  },
  3231: {
    reports: [{ firm: '中信投顧', target: 195, date: '2026/03/16' },
      { firm: '國內法人', target: 188, date: '2026/03/16' }],
    updatedAt: '2026/04/01',
    isNew: true,
  },
  3443: {
    reports: [
      { firm: '中信投顧', target: 3600, date: '2026/02' },
      { firm: '元大投顧', target: 3400, date: '2026/02' },
      { firm: '大摩', target: 3288, date: '2026/02' },
    ],
    updatedAt: '2026/02/04',
    isNew: true,
  },
  3491: {
    reports: [{ firm: '自行估算', target: 1600, date: '2026/03' }],
    updatedAt: '2026/03/17',
    isNew: false,
  },
  4583: {
    reports: [{ firm: '自行估算', target: 750, date: '2026/03' }],
    updatedAt: '2026/03/17',
    isNew: false,
  },
  6274: {
    reports: [{ firm: '中信投顧', target: 710, date: '2026/03/12' }],
    updatedAt: '2026/03/12',
    isNew: true,
  },
  6770: {
    reports: [{ firm: '自行估算', target: 100, date: '2026/03' }],
    updatedAt: '2026/03/17',
    isNew: false,
  },
  6862: {
    reports: [{ firm: '自行估算', target: 230, date: '2026/03' }],
    updatedAt: '2026/03/17',
    isNew: false,
  },
  8227: {
    reports: [{ firm: '中信投顧', target: 190, date: '2026/01/23' }],
    updatedAt: '2026/01/23',
    isNew: false,
  },
}

export const avgTarget = (code) => {
  const d = INIT_TARGETS[code]
  if (!d || !d.reports.length) return null
  return Math.round(d.reports.reduce((s, r) => s + r.target, 0) / d.reports.length)
}

// ── 產業/策略 metadata ──────────────────────────────────────────
export const STOCK_META = {
  // ── me 組合 ──
  '00637L': {
    industry: '中國ETF',
    strategy: 'ETF/指數',
    period: '短中',
    position: '戰術',
    leader: 'N/A',
  },
  '039108': {
    industry: '被動元件',
    strategy: '權證',
    period: '短',
    position: '戰術',
    leader: 'N/A',
    underlying: '禾伸堂',
  },
  '053848': {
    industry: '半導體設備',
    strategy: '權證',
    period: '短',
    position: '戰術',
    leader: 'N/A',
    underlying: '亞翔',
  },
  702157: {
    industry: '光通訊',
    strategy: '權證',
    period: '短',
    position: '戰術',
    leader: 'N/A',
    underlying: '華星光',
  },
  1503: { industry: '重電', strategy: '景氣循環', period: '中', position: '衛星', leader: '二線' },
  1717: {
    industry: 'PCB/材料',
    strategy: '景氣循環',
    period: '中',
    position: '衛星',
    leader: '龍頭',
    themes: ['ABF載板'],
  },
  2308: {
    industry: 'AI/伺服器',
    strategy: '成長股',
    period: '中長',
    position: '核心',
    leader: '龍頭',
    themes: ['AI伺服器', '資料中心', '電動車'],
  },
  2313: {
    industry: 'PCB/材料',
    strategy: '景氣循環',
    period: '中',
    position: '衛星',
    leader: '二線',
  },
  2543: { industry: '營建', strategy: '景氣循環', period: '中', position: '戰術', leader: '小型' },
  3006: {
    industry: 'IC/記憶體',
    strategy: '景氣循環',
    period: '短中',
    position: '戰術',
    leader: '小型',
  },
  3013: {
    industry: 'AI/伺服器',
    strategy: '成長股',
    period: '中',
    position: '衛星',
    leader: '小型',
    themes: ['AI伺服器'],
  },
  3017: {
    industry: 'AI/伺服器',
    strategy: '成長股',
    period: '中長',
    position: '核心',
    leader: '龍頭',
    themes: ['AI伺服器', '資料中心'],
  },
  3231: {
    industry: 'AI/伺服器',
    strategy: '成長股',
    period: '中',
    position: '衛星',
    leader: '大型',
    themes: ['AI伺服器', 'NVIDIA'],
  },
  3443: {
    industry: 'AI/伺服器',
    strategy: '成長股',
    period: '中長',
    position: '核心',
    leader: '龍頭',
    themes: ['AI伺服器', 'NVIDIA', 'CoWoS'],
  },
  3491: {
    industry: '光通訊',
    strategy: '成長股',
    period: '中長',
    position: '核心',
    leader: '小龍頭',
    themes: ['CPO', '低軌衛星', '資料中心'],
  },
  4583: {
    industry: '精密機械',
    strategy: '事件驅動',
    period: '中',
    position: '衛星',
    leader: '小型',
  },
  6274: {
    industry: 'PCB/材料',
    strategy: '景氣循環',
    period: '中',
    position: '衛星',
    leader: '二線',
    themes: ['AI伺服器'],
  },
  6770: {
    industry: 'IC/記憶體',
    strategy: '景氣循環',
    period: '中長',
    position: '衛星',
    leader: '二線',
  },
  6862: {
    industry: '連接器',
    strategy: '成長股',
    period: '中',
    position: '衛星',
    leader: '小型',
    themes: ['AI伺服器', 'NVIDIA'],
  },
  8227: {
    industry: '光通訊',
    strategy: '成長股',
    period: '中長',
    position: '衛星',
    leader: '小型',
    themes: ['CPO', '資料中心'],
  },
  // ── 金聯成 組合 ──
  '0050': {
    industry: '台股ETF',
    strategy: 'ETF/指數',
    period: '中長',
    position: '衛星',
    leader: 'N/A',
  },
  '00635U': {
    industry: '商品ETF',
    strategy: 'ETF/指數',
    period: '中',
    position: '戰術',
    leader: 'N/A',
  },
  '00918': {
    industry: '高股息ETF',
    strategy: 'ETF/指數',
    period: '中長',
    position: '衛星',
    leader: 'N/A',
  },
  '00981A': {
    industry: '主動型ETF',
    strategy: 'ETF/指數',
    period: '中長',
    position: '衛星',
    leader: 'N/A',
  },
  1799: {
    industry: '生技醫療',
    strategy: '轉型股',
    period: '中',
    position: '核心',
    leader: '小型',
  },
  1815: {
    industry: 'PCB/材料',
    strategy: '景氣循環',
    period: '中',
    position: '衛星',
    leader: '二線',
  },
  2489: {
    industry: '顯示器/光電',
    strategy: '轉型股',
    period: '中',
    position: '核心',
    leader: '中型',
  },
  3167: {
    industry: '精密機械',
    strategy: '成長股',
    period: '中',
    position: '衛星',
    leader: '小龍頭',
  },
  4562: {
    industry: '精密機械',
    strategy: '景氣循環',
    period: '中',
    position: '衛星',
    leader: '小型',
  },
  6446: {
    industry: '生技醫療',
    strategy: '成長股',
    period: '中長',
    position: '核心',
    leader: '龍頭',
  },
  7799: {
    industry: '生技醫療',
    strategy: '成長股',
    period: '中長',
    position: '核心',
    leader: '小龍頭',
  },
  7865: {
    industry: '環保/循環',
    strategy: '價值股',
    period: '中長',
    position: '核心',
    leader: '小龍頭',
  },
  8074: {
    industry: 'PCB/材料',
    strategy: '景氣循環',
    period: '中',
    position: '衛星',
    leader: '小型',
  },
  8096: {
    industry: '電子通路',
    strategy: '成長股',
    period: '中',
    position: '衛星',
    leader: '中型',
  },
}

// 產業色彩映射 — 提亮版（文字用，需在 #283D3B 上可讀）
export const IND_COLOR = {
  'AI/伺服器': C.teal,
  光通訊: C.cyan,
  'PCB/材料': C.amber,
  'IC/記憶體': C.lavender,
  被動元件: C.orange,
  重電: C.up,
  營建: C.olive,
  精密機械: C.stone,
  連接器: C.mint,
  中國ETF: C.rose,
  半導體設備: C.choco,
  // 金聯成 組合新增產業
  生技醫療: C.up,
  台股ETF: C.blue,
  高股息ETF: C.blue,
  主動型ETF: C.blue,
  商品ETF: C.amber,
  '顯示器/光電': C.rose,
  '環保/循環': C.olive,
  電子通路: C.lavender,
}

// ── 初始持倉 ────────────────────────────────────────────────────
export const INIT_HOLDINGS = [
  {
    code: '00637L',
    name: '滬深300正2',
    qty: 141,
    price: 19.96,
    cost: 18.99,
    value: 2814,
    pnl: 134,
    pct: 5.01,
    type: 'ETF',
  },
  {
    code: '039108',
    name: '禾伸堂元富57購',
    qty: 8000,
    price: 0.79,
    cost: 0.9925,
    value: 6320,
    pnl: -824,
    pct: -10.35,
    type: '權證',
    expire: '2026/07',
    targetPrice: 1.98,
  },
  {
    code: '053848',
    name: '亞翔凱基5B購',
    qty: 8000,
    price: 2.23,
    cost: 1.81,
    value: 17840,
    pnl: 3234,
    pct: 22.32,
    type: '權證',
  },
  {
    code: '702157',
    name: '華星光元大58購',
    qty: 4000,
    price: 3.35,
    cost: 1.29,
    value: 13400,
    pnl: 8167,
    pct: 157.66,
    type: '權證',
  },
  {
    code: '1503',
    name: '士電',
    qty: 9,
    price: 205,
    cost: 229.5,
    value: 1845,
    pnl: -227,
    pct: -10.99,
    type: '股票',
  },
  {
    code: '1717',
    name: '長興',
    qty: 43,
    price: 63.7,
    cost: 66.1,
    value: 2737,
    pnl: -118,
    pct: -4.15,
    type: '股票',
  },
  {
    code: '2308',
    name: '台達電',
    qty: 2,
    price: 1440,
    cost: 1287.5,
    value: 2880,
    pnl: 293,
    pct: 11.37,
    type: '股票',
  },
  {
    code: '2313',
    name: '華通',
    qty: 40,
    price: 236.5,
    cost: 187.5,
    value: 9457,
    pnl: 1920,
    pct: 25.58,
    type: '股票',
  },
  {
    code: '2543',
    name: '皇昌',
    qty: 6,
    price: 71.6,
    cost: 78.3,
    value: 429,
    pnl: -43,
    pct: -9.15,
    type: '股票',
  },
  {
    code: '3006',
    name: '晶豪科',
    qty: 12,
    price: 194.5,
    cost: 164,
    value: 2334,
    pnl: 357,
    pct: 18.13,
    type: '股票',
    alert: '⚡出場區間到',
  },
  {
    code: '3013',
    name: '晟銘電',
    qty: 29,
    price: 99,
    cost: 125.91,
    value: 2871,
    pnl: -791,
    pct: -21.65,
    type: '股票',
  },
  {
    code: '3017',
    name: '奇鋐',
    qty: 2,
    price: 1905,
    cost: 1400,
    value: 3810,
    pnl: 997,
    pct: 35.59,
    type: '股票',
  },
  {
    code: '3231',
    name: '緯創',
    qty: 11,
    price: 134,
    cost: 134.55,
    value: 1474,
    pnl: -14,
    pct: -0.94,
    type: '股票',
  },
  {
    code: '3443',
    name: '創意',
    qty: 3,
    price: 2290,
    cost: 2566.67,
    value: 6870,
    pnl: -854,
    pct: -11.09,
    type: '股票',
  },
  {
    code: '3491',
    name: '昇達科',
    qty: 3,
    price: 1445,
    cost: 1276.67,
    value: 4335,
    pnl: 487,
    pct: 12.71,
    type: '股票',
  },
  {
    code: '4583',
    name: '台灣精銳',
    qty: 5,
    price: 629,
    cost: 734,
    value: 3145,
    pnl: -536,
    pct: -14.6,
    type: '股票',
  },
  {
    code: '6274',
    name: '台燿',
    qty: 3,
    price: 505,
    cost: 507,
    value: 1515,
    pnl: -12,
    pct: -0.79,
    type: '股票',
    alert: '法說',
  },
  {
    code: '6770',
    name: '力積電',
    qty: 20,
    price: 71.7,
    cost: 68.05,
    value: 1433,
    pnl: 63,
    pct: 4.62,
    type: '股票',
  },
  {
    code: '6862',
    name: '三集瑞-KY',
    qty: 17,
    price: 209.5,
    cost: 197.82,
    value: 3560,
    pnl: 182,
    pct: 5.41,
    type: '股票',
  },
  {
    code: '8227',
    name: '巨有科技',
    qty: 21,
    price: 128,
    cost: 146.57,
    value: 2688,
    pnl: -403,
    pct: -13.08,
    type: '股票',
  },
]

// ── 金聯成 組合初始持倉 ──────────────────────────────────────────
export const INIT_HOLDINGS_JINLIANCHENG = [
  {
    code: '0050',
    name: '元大台灣50',
    qty: 52,
    price: 75.9,
    cost: 73.54,
    value: 3947,
    pnl: 100,
    pct: 2.61,
    type: 'ETF',
  },
  {
    code: '00635U',
    name: '期元大S&P黃金',
    qty: 36,
    price: 50.05,
    cost: 53.97,
    value: 1802,
    pnl: -162,
    pct: -8.35,
    type: 'ETF',
  },
  {
    code: '00918',
    name: '大華優利高填息30',
    qty: 169,
    price: 22.58,
    cost: 23.34,
    value: 3816,
    pnl: -151,
    pct: -3.83,
    type: 'ETF',
  },
  {
    code: '00981A',
    name: '主動統一台股增長',
    qty: 309,
    price: 21.02,
    cost: 19.22,
    value: 6495,
    pnl: 529,
    pct: 8.91,
    type: 'ETF',
  },
  {
    code: '2489',
    name: '瑞軒',
    qty: 56000,
    price: 38.65,
    cost: 42.27,
    value: 2164400,
    pnl: -212140,
    pct: -8.96,
    type: '股票',
  },
  {
    code: '3167',
    name: '大量',
    qty: 1000,
    price: 345.0,
    cost: 350.5,
    value: 345000,
    pnl: -7024,
    pct: -2.0,
    type: '股票',
  },
  {
    code: '4562',
    name: '穎漢',
    qty: 7000,
    price: 32.6,
    cost: 33.33,
    value: 228200,
    pnl: -6089,
    pct: -2.61,
    type: '股票',
  },
  {
    code: '6446',
    name: '藥華藥',
    qty: 4100,
    price: 640.0,
    cost: 708.32,
    value: 2624000,
    pnl: -291742,
    pct: -10.05,
    type: '股票',
  },
  {
    code: '7799',
    name: '禾榮科',
    qty: 2951,
    price: 410.5,
    cost: 867.69,
    value: 1211396,
    pnl: -1354518,
    pct: -52.9,
    type: '股票',
  },
  {
    code: '1799',
    name: '易威',
    qty: 59000,
    price: 37.8,
    cost: 79.53,
    value: 2230200,
    pnl: -2471836,
    pct: -52.68,
    type: '股票',
  },
  {
    code: '1815',
    name: '富喬',
    qty: 6000,
    price: 102.0,
    cost: 108.74,
    value: 612000,
    pnl: -43134,
    pct: -6.61,
    type: '股票',
  },
  {
    code: '3491',
    name: '昇達科',
    qty: 140,
    price: 1450.0,
    cost: 1442.76,
    value: 203000,
    pnl: 115,
    pct: 0.06,
    type: '股票',
  },
  {
    code: '8074',
    name: '鉅橡',
    qty: 4000,
    price: 61.1,
    cost: 66.19,
    value: 244400,
    pnl: -21456,
    pct: -8.1,
    type: '股票',
  },
  {
    code: '8096',
    name: '擎亞',
    qty: 5500,
    price: 87.1,
    cost: 74.8,
    value: 479050,
    pnl: 65548,
    pct: 15.93,
    type: '股票',
  },
  {
    code: '7865',
    name: '金聯成',
    qty: 106543,
    price: 49.5,
    cost: 8.25,
    value: 5273879,
    pnl: 4371506,
    pct: 497.31,
    type: '股票',
  },
]

export const INIT_WATCHLIST = [
  {
    code: '1513',
    name: '中興電',
    price: 158.5,
    target: 193,
    status: '等Q4財報',
    catalyst: '3–4月財報',
    scKey: 'amber',
    note: '積極163–165元；保守155–160元；催化：台電GIS+台積電',
  },
  {
    code: '4588',
    name: '玖鼎電力',
    price: 69.1,
    target: 154,
    status: '持有中',
    catalyst: '台電電表訂單',
    scKey: 'olive',
    note: '訂單排到2028；現價已偏高不追；持有者繼續抱',
  },
  {
    code: '6274',
    name: '台燿',
    price: 505,
    target: 710,
    status: '⚡法說追蹤',
    catalyst: '3/18法說+財報',
    scKey: 'up',
    note: '成本507；毛利率回沖→補足2/3；展望差→停損430',
  },
]

export const RELAY_PLAN = {
  title: '2026 三檔接力投資計畫',
  summary: '晶豪科先收割，力積電等月營收確認，台燿走長波段。',
  thesis: [
    '晶豪科是 DDR3 短缺的第一棒，先吃 IC 設計端的漲價爆發。',
    '力積電是第二棒，等 2H26 代工費上漲反映到營收再加碼。',
    '台燿是第三棒，走 AI 伺服器 / ASIC / 產能擴張的中長線故事。',
  ],
  quickStates: [
    { label: '現在', text: '晶豪科 175–185 分批出；台燿 450–470 先進 1/3', tone: 'up' },
    { label: '6–7月', text: '力積電等月營收年增顯著加速再加碼', tone: 'amber' },
    { label: '全年', text: '台燿法說確認後續抱，主線看向 2027', tone: 'blue' },
  ],
  legs: [
    {
      code: '3006',
      name: '晶豪科',
      role: '第一棒',
      tone: 'up',
      status: '出場管理',
      window: '現在 - Q2 財報前',
      action: '175–185 元分批出，不等 200 元',
      trigger: 'Q2 財報前 1–2 週最遲全部出清',
      stop: '148 元',
      bullets: [
        'DDR3 短缺題材爆發，4Q25 EPS 3.68 元遠超預期。',
        '2026 Q2 可能是獲利高峰，之後毛利率有被代工費擠壓風險。',
        '市場反應前先收割，避免高峰過後回吐。',
      ],
    },
    {
      code: '6770',
      name: '力積電',
      role: '第二棒',
      tone: 'amber',
      status: '待命觀察',
      window: '晶豪科出場後 / 約 6–7 月',
      action: '看到月營收年增明顯加速再加碼',
      trigger: 'DDR3 漲價開始反映到代工端財報',
      stop: '進場前重設技術停損',
      bullets: [
        '吃的是第二段：晶豪科上游漲價流入力積電營收。',
        '同一題材，但從成本端承壓切換到代工端受益。',
        '沒看到營收轉強前，先不急著加碼。',
      ],
    },
    {
      code: '6274',
      name: '台燿',
      role: '第三棒',
      tone: 'blue',
      status: '分批布局',
      window: '現在 - 2027',
      action: '450–470 先進 1/3；法說後再決定是否補齊',
      trigger: '3/18 法說確認毛利率回沖與展望',
      stop: '430 元',
      bullets: [
        'AI 伺服器 CCL、800G 交換器與 ASIC 升級是主線。',
        'Q1→Q4 EPS 預估逐季加速，和晶豪科前高後低互補。',
        '若法說樂觀可補齊，若保守就縮小部位或停損觀望。',
      ],
    },
  ],
  riskMatrix: [
    { scenario: '全部如預期', action: '晶豪科 Q2 前出；力積電 6–7 月加碼；台燿續抱至 2027。' },
    { scenario: '晶豪科跌破 148', action: '立即停損，力積電先不加碼，台燿獨立評估。' },
    { scenario: '台燿法說保守', action: '不影響晶豪科 / 力積電主線，台燿縮小部位或停損 430。' },
    { scenario: '大盤系統性崩跌', action: '晶豪科先砍保現金，力積電零股不動，台燿嚴守 430。' },
  ],
  indicators: [
    {
      code: '3006',
      name: '晶豪科',
      when: '每月 10 日 / 5–6 月',
      what: '月營收是否維持高檔；市場是否提前反映 Q2 高峰。',
    },
    {
      code: '6770',
      name: '力積電',
      when: '6–7 月月營收',
      what: '年增率是否顯著加速（>30% 更有說服力）。',
    },
    {
      code: '6274',
      name: '台燿',
      when: '3/18 法說 / 每季財報 / 泰國二期',
      what: '毛利率回沖、EPS 是否逐季加速、產能是否如期達標。',
    },
  ],
  allocations: [
    { phase: '現在（3月）', target: '晶豪科', plan: '用緯創賣出資金，分批完成約 17 張部位。' },
    { phase: '現在（3月）', target: '台燿', plan: '新資金先進三分之一，法說後再決定補足。' },
    {
      phase: '6–7月後',
      target: '力積電 / 台燿',
      plan: '晶豪科獲利分流，一部分轉力積電，一部分視台燿法說補足。',
    },
  ],
}

export const RELAY_PLAN_CODES = new Set(RELAY_PLAN.legs.map((item) => item.code))

export const EVENTS = [
  // 3/26 更新：移除已過期事件
  // 舊的「今日」硬編碼事件已移除，改以實際事件日期與狀態判斷

  {
    date: '每月10日',
    label: '月營收公布',
    sub: '晶豪科最關鍵——確認DDR3高檔維持',
    urgent: false,
    type: '營收',
  },
  {
    date: '3/27前',
    label: '3月最後一週財報',
    sub: '注意是否有最後衝刺行情',
    urgent: false,
    type: '財報',
  },
  {
    date: '4/1前',
    label: '中小型股全年財報',
    sub: '長興、華通、晟銘電、昇達科、台灣精銳、力積電',
    urgent: false,
    type: '財報',
  },
  {
    date: '3–4月',
    label: '中興電 Q4財報 + 法說',
    sub: '催化劑：台電GIS發包 + 台積電訂單',
    urgent: false,
    type: '催化',
  },
  {
    date: 'Q2前',
    label: '晶豪科 全數出場',
    sub: 'Q1財報前最遲出清；資金轉台燿/力積電',
    urgent: false,
    type: '操作',
  },
  {
    date: '2026/07',
    label: '禾伸堂元富57購 到期',
    sub: '目標獲利100%（約1.98元）；留意時間價值遞減',
    urgent: false,
    type: '權證',
  },
  {
    date: 'Q2',
    label: '台燿 泰國二期產能確認',
    sub: '月產能是否達260萬張（目標710元關鍵假設）',
    urgent: false,
    type: '催化',
  },
  {
    date: '6–7月',
    label: '力積電 加碼評估',
    sub: '月營收年增>30%才加碼',
    urgent: false,
    type: '操作',
  },
  {
    date: 'Q3起',
    label: '緯創 VR爬坡',
    sub: '3Q26帶來4–5個月完整營收貢獻',
    urgent: false,
    type: '催化',
  },
  {
    date: '持續',
    label: '美國關稅談判進度',
    sub: '15%協議已達成；後續執行細節影響科技出口股',
    urgent: false,
    type: '總經',
  },
  {
    date: '持續',
    label: 'Fed 利率政策',
    sub: '降息預期影響外資流向台股',
    urgent: false,
    type: '總經',
  },
]

// ── 事件分析資料庫 ────────────────────────────────────────────────
// status: "past"=已發生 / "pending"=未發生
// pred: "up"=預測漲 / "down"=預測跌 / "neutral"=中性
// actual: "up"/"down"/"neutral"/null（null=尚未驗證）
// correct: true/false/null
export const NEWS_EVENTS = [
  // ── 已發生 ──
  {
    id: 1,
    date: '2026/03/13',
    status: 'past',
    title: '三星記憶體工人罷工威脅，DDR3 供給缺口擴大',
    detail:
      '三星韓國工廠工會威脅全面罷工，市場預期DRAM供給將進一步吃緊，利基型記憶體（DDR3）受矚目。',
    stocks: ['晶豪科 3006'],
    pred: 'up',
    predReason: 'DDR3供給端收縮，晶豪科作為利基型記憶體IC設計受直接利多。',
    actual: 'up',
    actualNote: '晶豪科連續兩日漲停，從161元急拉至177元，驗證預測正確。',
    correct: true,
  },
  {
    id: 2,
    date: '2026/03/16',
    status: 'past',
    title: '晶豪科 4Q25 EPS 3.68元，遠超市場預期 0.18元',
    detail:
      '華南投顧發出研究報告，揭露4Q25每股盈餘3.68元，市場預估僅0.18元，超預期約20倍。目標價200元。',
    stocks: ['晶豪科 3006'],
    pred: 'up',
    predReason: '財報大幅超預期是最強催化劑，法人勢必上調目標價，資金將快速湧入。',
    actual: 'up',
    actualNote: '報告發出後三日股價從145元漲至194.5元，漲幅約34%。',
    correct: true,
  },
  {
    id: 3,
    date: '2026/03/13',
    status: 'past',
    title: '台燿 財報前外資連續賣超，股價從530跌至450',
    detail: '台燿3月初從高點583元修正，三大法人籌碼持續綠色，財報前賣壓明顯。',
    stocks: ['台燿 6274'],
    pred: 'down',
    predReason: '財報前獲利了結賣壓是常見型態，加上毛利率疑慮，短期壓力大。',
    actual: 'down',
    actualNote: '股價從583跌至約450元，修正約25%，符合預測方向。',
    correct: true,
  },
  {
    id: 4,
    date: '2026/03/16',
    status: 'past',
    title: '台燿連兩日籌碼綠色但股價逆勢漲近10%',
    detail: '外資+自營商合計賣超，但散戶財報前卡位情緒推動股價接近漲停。',
    stocks: ['台燿 6274'],
    pred: 'up',
    predReason: '財報日前6天，散戶預期法說樂觀，提前卡位效應。',
    actual: 'up',
    actualNote: '單日漲9.94%，收497.5元，驗證財報前卡位邏輯。',
    correct: true,
  },
  {
    id: 5,
    date: '2026/03/16',
    status: 'past',
    title: '緯創 4Q25 法說：毛利率受GB機櫃出貨組合壓縮',
    detail: '4Q25毛利率5.62%，QoQ降177bps，主因GB系列機櫃佔比提升。目標價從217元下調至195元。',
    stocks: ['緯創 3231'],
    pred: 'down',
    predReason: '目標價下調，毛利率不如預期，短期壓力。',
    actual: 'down',
    actualNote: '法說後股價維持在134元附近偏弱，中信下調目標價至195元印證。',
    correct: true,
  },

  // ── 未發生 / 進行中 ──
  {
    id: 6,
    date: '2026/03/18',
    status: 'pending',
    title: '台燿 Q4財報法說會',
    detail: '關鍵觀察：毛利率是否確認回沖、AI CCL產品展望、泰國二期產能時程。',
    stocks: ['台燿 6274'],
    pred: 'up',
    predReason:
      '中信預估2026F EPS逐季加速（4.21→5.49→7.37→8.72），若法說確認此路徑，市場將重新定價。',
    actual: null,
    actualNote: '',
    correct: null,
  },
  {
    id: 7,
    date: '2026/03–04月',
    status: 'pending',
    title: '中興電 Q4全年財報公布',
    detail: 'FactSet共識EPS 10.43元，7位分析師全數強力買進，目標價193.4元。台電GIS招標動向是關鍵。',
    stocks: ['中興電 1513'],
    pred: 'up',
    predReason: '財報若符合共識，加上台電基礎建設招標持續，股價有望從158.5元向193元靠攏。',
    actual: null,
    actualNote: '',
    correct: null,
  },
  {
    id: 8,
    date: '2026/Q2',
    status: 'pending',
    title: '晶豪科 Q2 EPS高峰季，毛利率55.7%預估',
    detail:
      '2026 Q2 EPS預估11.51元，為全年最高峰。力積電代工費2H26漲100%，毛利率將在Q3後回落至32–34%。',
    stocks: ['晶豪科 3006'],
    pred: 'up',
    predReason: '市場將在Q1財報後開始定價Q2高峰，股價有望提前反映。出場窗口在財報前1–2週。',
    actual: null,
    actualNote: '',
    correct: null,
  },
  {
    id: 9,
    date: '2026/Q2',
    status: 'pending',
    title: '台燿 泰國二期產能是否達260萬張月產',
    detail: '台燿目前月產能約178萬張，二期完工後目標260萬張，是2026年EPS加速的核心假設。',
    stocks: ['台燿 6274'],
    pred: 'up',
    predReason: '若如期達產，800G交換器與AI伺服器CCL訂單能見度大增，目標價710元更有說服力。',
    actual: null,
    actualNote: '',
    correct: null,
  },
  {
    id: 10,
    date: '持續',
    status: 'pending',
    title: '美國對台半導體關稅談判（15%協議後續執行）',
    detail: '台美已達成15%關稅協議，但執行細節與豁免清單仍在協商，科技出口股受牽連。',
    stocks: ['奇鋐 3017', '台達電 2308', '緯創 3231', '創意 3443'],
    pred: 'neutral',
    predReason: '協議已達成降低最壞情境，但執行不確定性讓外資偏謹慎，短期偏中性到略偏空。',
    actual: null,
    actualNote: '',
    correct: null,
  },
  {
    id: 11,
    date: '2026/07',
    status: 'pending',
    title: '禾伸堂元富57購 到期',
    detail:
      '目前持倉8,000股，均成本0.9925元，目標翻倍（約1.98元）。權證無停損設定，時間價值越近到期遞減越快。',
    stocks: ['禾伸堂 2481（標的）'],
    pred: 'up',
    predReason:
      '被動元件族群動能上來，禾伸堂本股動能啟動。但須在Q2前確認趨勢，否則時間成本侵蝕獲利空間。',
    actual: null,
    actualNote: '',
    correct: null,
  },
  {
    id: 12,
    date: '2026/Q3',
    status: 'pending',
    title: '緯創 VR 系列爬坡（NV Vera Rubin）',
    detail: 'VR系列減少線材組裝、組裝性更佳，預計3Q26開始帶來4–5個月完整營收貢獻，ASP將上揚。',
    stocks: ['緯創 3231'],
    pred: 'up',
    predReason: '若爬坡如期，3Q26起營收加速，毛利率組合改善，現價134元相對目標195元仍有空間。',
    actual: null,
    actualNote: '',
    correct: null,
  },
]

// 金聯成 組合目標價（僅收錄查到的法人/分析師共識）
export const INIT_TARGETS_JINLIANCHENG = {
  6446: {
    reports: [{ firm: '分析師', target: 1060, date: '2026/03' }],
    updatedAt: '2026/03/23',
    isNew: true,
  },
}
