// ── 事件分析資料庫 ────────────────────────────────────────────────
// status: "past"=已發生 / "pending"=未發生
// pred: "up"=預測漲 / "down"=預測跌 / "neutral"=中性
// actual: "up"/"down"/"neutral"/null（null=尚未驗證）
// correct: true/false/null
export const NEWS_EVENTS = [
  // ── 已發生 ──
  {
    id: 1,
    date: '2026/03/13',
    status: 'past',
    title: '三星記憶體工人罷工威脅，DDR3 供給缺口擴大',
    detail:
      '三星韓國工廠工會威脅全面罷工，市場預期DRAM供給將進一步吃緊，利基型記憶體（DDR3）受矚目。',
    stocks: ['晶豪科 3006'],
    pred: 'up',
    predReason: 'DDR3供給端收縮，晶豪科作為利基型記憶體IC設計受直接利多。',
    actual: 'up',
    actualNote: '晶豪科連續兩日漲停，從161元急拉至177元，驗證預測正確。',
    correct: true,
  },
  {
    id: 2,
    date: '2026/03/16',
    status: 'past',
    title: '晶豪科 4Q25 EPS 3.68元，遠超市場預期 0.18元',
    detail:
      '華南投顧發出研究報告，揭露4Q25每股盈餘3.68元，市場預估僅0.18元，超預期約20倍。目標價200元。',
    stocks: ['晶豪科 3006'],
    pred: 'up',
    predReason: '財報大幅超預期是最強催化劑，法人勢必上調目標價，資金將快速湧入。',
    actual: 'up',
    actualNote: '報告發出後三日股價從145元漲至194.5元，漲幅約34%。',
    correct: true,
  },
  {
    id: 3,
    date: '2026/03/13',
    status: 'past',
    title: '台燿 財報前外資連續賣超，股價從530跌至450',
    detail: '台燿3月初從高點583元修正，三大法人籌碼持續綠色，財報前賣壓明顯。',
    stocks: ['台燿 6274'],
    pred: 'down',
    predReason: '財報前獲利了結賣壓是常見型態，加上毛利率疑慮，短期壓力大。',
    actual: 'down',
    actualNote: '股價從583跌至約450元，修正約25%，符合預測方向。',
    correct: true,
  },
  {
    id: 4,
    date: '2026/03/16',
    status: 'past',
    title: '台燿連兩日籌碼綠色但股價逆勢漲近10%',
    detail: '外資+自營商合計賣超，但散戶財報前卡位情緒推動股價接近漲停。',
    stocks: ['台燿 6274'],
    pred: 'up',
    predReason: '財報日前6天，散戶預期法說樂觀，提前卡位效應。',
    actual: 'up',
    actualNote: '單日漲9.94%，收497.5元，驗證財報前卡位邏輯。',
    correct: true,
  },
  {
    id: 5,
    date: '2026/03/16',
    status: 'past',
    title: '緯創 4Q25 法說：毛利率受GB機櫃出貨組合壓縮',
    detail: '4Q25毛利率5.62%，QoQ降177bps，主因GB系列機櫃佔比提升。目標價從217元下調至195元。',
    stocks: ['緯創 3231'],
    pred: 'down',
    predReason: '目標價下調，毛利率不如預期，短期壓力。',
    actual: 'down',
    actualNote: '法說後股價維持在134元附近偏弱，中信下調目標價至195元印證。',
    correct: true,
  },

  // ── 未發生 / 進行中 ──
  {
    id: 6,
    date: '2026/03/18',
    status: 'pending',
    title: '台燿 Q4財報法說會',
    detail: '關鍵觀察：毛利率是否確認回沖、AI CCL產品展望、泰國二期產能時程。',
    stocks: ['台燿 6274'],
    pred: 'up',
    predReason:
      '中信預估2026F EPS逐季加速（4.21→5.49→7.37→8.72），若法說確認此路徑，市場將重新定價。',
    actual: null,
    actualNote: '',
    correct: null,
  },
  {
    id: 7,
    date: '2026/03–04月',
    status: 'pending',
    title: '中興電 Q4全年財報公布',
    detail: 'FactSet共識EPS 10.43元，7位分析師全數強力買進，目標價193.4元。台電GIS招標動向是關鍵。',
    stocks: ['中興電 1513'],
    pred: 'up',
    predReason: '財報若符合共識，加上台電基礎建設招標持續，股價有望從158.5元向193元靠攏。',
    actual: null,
    actualNote: '',
    correct: null,
  },
  {
    id: 8,
    date: '2026/Q2',
    status: 'pending',
    title: '晶豪科 Q2 EPS高峰季，毛利率55.7%預估',
    detail:
      '2026 Q2 EPS預估11.51元，為全年最高峰。力積電代工費2H26漲100%，毛利率將在Q3後回落至32–34%。',
    stocks: ['晶豪科 3006'],
    pred: 'up',
    predReason: '市場將在Q1財報後開始定價Q2高峰，股價有望提前反映。出場窗口在財報前1–2週。',
    actual: null,
    actualNote: '',
    correct: null,
  },
  {
    id: 9,
    date: '2026/Q2',
    status: 'pending',
    title: '台燿 泰國二期產能是否達260萬張月產',
    detail: '台燿目前月產能約178萬張，二期完工後目標260萬張，是2026年EPS加速的核心假設。',
    stocks: ['台燿 6274'],
    pred: 'up',
    predReason: '若如期達產，800G交換器與AI伺服器CCL訂單能見度大增，目標價710元更有說服力。',
    actual: null,
    actualNote: '',
    correct: null,
  },
  {
    id: 10,
    date: '持續',
    status: 'pending',
    title: '美國對台半導體關稅談判（15%協議後續執行）',
    detail: '台美已達成15%關稅協議，但執行細節與豁免清單仍在協商，科技出口股受牽連。',
    stocks: ['奇鋐 3017', '台達電 2308', '緯創 3231', '創意 3443'],
    pred: 'neutral',
    predReason: '協議已達成降低最壞情境，但執行不確定性讓外資偏謹慎，短期偏中性到略偏空。',
    actual: null,
    actualNote: '',
    correct: null,
  },
  {
    id: 11,
    date: '2026/07',
    status: 'pending',
    title: '禾伸堂元富57購 到期',
    detail:
      '目前持倉8,000股，均成本0.9925元，目標翻倍（約1.98元）。權證無停損設定，時間價值越近到期遞減越快。',
    stocks: ['禾伸堂 2481（標的）'],
    pred: 'up',
    predReason:
      '被動元件族群動能上來，禾伸堂本股動能啟動。但須在Q2前確認趨勢，否則時間成本侵蝕獲利空間。',
    actual: null,
    actualNote: '',
    correct: null,
  },
  {
    id: 12,
    date: '2026/Q3',
    status: 'pending',
    title: '緯創 VR 系列爬坡（NV Vera Rubin）',
    detail: 'VR系列減少線材組裝、組裝性更佳，預計3Q26開始帶來4–5個月完整營收貢獻，ASP將上揚。',
    stocks: ['緯創 3231'],
    pred: 'up',
    predReason: '若爬坡如期，3Q26起營收加速，毛利率組合改善，現價134元相對目標195元仍有空間。',
    actual: null,
    actualNote: '',
    correct: null,
  },
]

export const RELAY_PLAN = {
  title: '2026 三檔接力投資計畫',
  summary: '晶豪科先收割，力積電等月營收確認，台燿走長波段。',
  thesis: [
    '晶豪科是 DDR3 短缺的第一棒，先吃 IC 設計端的漲價爆發。',
    '力積電是第二棒，等 2H26 代工費上漲反映到營收再加碼。',
    '台燿是第三棒，走 AI 伺服器 / ASIC / 產能擴張的中長線故事。',
  ],
  quickStates: [
    { label: '現在', text: '晶豪科 175–185 分批出；台燿 450–470 先進 1/3', tone: 'up' },
    { label: '6–7月', text: '力積電等月營收年增顯著加速再加碼', tone: 'amber' },
    { label: '全年', text: '台燿法說確認後續抱，主線看向 2027', tone: 'blue' },
  ],
  legs: [
    {
      code: '3006',
      name: '晶豪科',
      role: '第一棒',
      tone: 'up',
      status: '出場管理',
      window: '現在 - Q2 財報前',
      action: '175–185 元分批出，不等 200 元',
      trigger: 'Q2 財報前 1–2 週最遲全部出清',
      stop: '148 元',
      bullets: [
        'DDR3 短缺題材爆發，4Q25 EPS 3.68 元遠超預期。',
        '2026 Q2 可能是獲利高峰，之後毛利率有被代工費擠壓風險。',
        '市場反應前先收割，避免高峰過後回吐。',
      ],
    },
    {
      code: '6770',
      name: '力積電',
      role: '第二棒',
      tone: 'amber',
      status: '待命觀察',
      window: '晶豪科出場後 / 約 6–7 月',
      action: '看到月營收年增明顯加速再加碼',
      trigger: 'DDR3 漲價開始反映到代工端財報',
      stop: '進場前重設技術停損',
      bullets: [
        '吃的是第二段：晶豪科上游漲價流入力積電營收。',
        '同一題材，但從成本端承壓切換到代工端受益。',
        '沒看到營收轉強前，先不急著加碼。',
      ],
    },
    {
      code: '6274',
      name: '台燿',
      role: '第三棒',
      tone: 'blue',
      status: '分批布局',
      window: '現在 - 2027',
      action: '450–470 先進 1/3；法說後再決定是否補齊',
      trigger: '3/18 法說確認毛利率回沖與展望',
      stop: '430 元',
      bullets: [
        'AI 伺服器 CCL、800G 交換器與 ASIC 升級是主線。',
        'Q1→Q4 EPS 預估逐季加速，和晶豪科前高後低互補。',
        '若法說樂觀可補齊，若保守就縮小部位或停損觀望。',
      ],
    },
  ],
  riskMatrix: [
    { scenario: '全部如預期', action: '晶豪科 Q2 前出；力積電 6–7 月加碼；台燿續抱至 2027。' },
    { scenario: '晶豪科跌破 148', action: '立即停損，力積電先不加碼，台燿獨立評估。' },
    { scenario: '台燿法說保守', action: '不影響晶豪科 / 力積電主線，台燿縮小部位或停損 430。' },
    { scenario: '大盤系統性崩跌', action: '晶豪科先砍保現金，力積電零股不動，台燿嚴守 430。' },
  ],
  indicators: [
    {
      code: '3006',
      name: '晶豪科',
      when: '每月 10 日 / 5–6 月',
      what: '月營收是否維持高檔；市場是否提前反映 Q2 高峰。',
    },
    {
      code: '6770',
      name: '力積電',
      when: '6–7 月月營收',
      what: '年增率是否顯著加速（>30% 更有說服力）。',
    },
    {
      code: '6274',
      name: '台燿',
      when: '3/18 法說 / 每季財報 / 泰國二期',
      what: '毛利率回沖、EPS 是否逐季加速、產能是否如期達標。',
    },
  ],
  allocations: [
    { phase: '現在（3月）', target: '晶豪科', plan: '用緯創賣出資金，分批完成約 17 張部位。' },
    { phase: '現在（3月）', target: '台燿', plan: '新資金先進三分之一，法說後再決定補足。' },
    {
      phase: '6–7月後',
      target: '力積電 / 台燿',
      plan: '晶豪科獲利分流，一部分轉力積電，一部分視台燿法說補足。',
    },
  ],
}

export const RELAY_PLAN_CODES = new Set(RELAY_PLAN.legs.map((item) => item.code))
